export const cppChallenges = [
  // Stage 1: C++ Fundamentals & I/O
  {
    title: 'Hello C++ Master',
    description: 'Write a C++ program using `#include <iostream>` that prints `"Hello, C++!"` to standard output.',
    language: 'cpp',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'C++ Fundamentals & I/O',
    order: 1,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '', expected: 'Hello, C++!', isHidden: false },
      { input: 'init', expected: 'Hello, C++!', isHidden: true },
    ],
    examples: [
      { input: '(none)', output: 'Hello, C++!', explanation: 'std::cout prints the greeting string.' },
    ],
    constraints: 'Exact character matching.',
    xpReward: 75,
    coinReward: 20,
  },
  {
    title: 'Sum of Two Numbers in C++',
    description: 'Read two integers `a` and `b` using `std::cin` and print their sum to `std::cout`.',
    language: 'cpp',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'C++ Fundamentals & I/O',
    order: 2,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '7 14', expected: '21', isHidden: false },
      { input: '-10 25', expected: '15', isHidden: false },
      { input: '1000 5000', expected: '6000', isHidden: true },
    ],
    examples: [
      { input: '7 14', output: '21', explanation: '7 + 14 = 21' },
    ],
    constraints: '-10^9 <= a, b <= 10^9',
    xpReward: 80,
    coinReward: 20,
  },
  {
    title: 'Simple Calculator Switch',
    description: 'Read a double `a`, an operator character `op` (`+`, `-`, `*`, `/`), and a double `b` from standard input (e.g. `10 + 5`). Compute and print the result formatted to 2 decimal places.',
    language: 'cpp',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'C++ Fundamentals & I/O',
    order: 3,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '10 + 5', expected: '15.00', isHidden: false },
      { input: '7 * 6', expected: '42.00', isHidden: false },
      { input: '10 / 4', expected: '2.50', isHidden: true },
      { input: '25 - 8', expected: '17.00', isHidden: true },
    ],
    examples: [
      { input: '10 + 5', output: '15.00', explanation: '10 + 5 = 15.00' },
    ],
    constraints: 'Divisor != 0',
    xpReward: 85,
    coinReward: 20,
  },
  {
    title: 'Bitwise Odd or Even',
    description: 'Read an integer `n` from standard input. Using the bitwise AND operator (`n & 1`), print `"Even"` if the number is even, or `"Odd"` if the number is odd.',
    language: 'cpp',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'C++ Fundamentals & I/O',
    order: 4,
    difficulty: 'easy',
    category: 'bitwise',
    testCases: [
      { input: '8', expected: 'Even', isHidden: false },
      { input: '13', expected: 'Odd', isHidden: false },
      { input: '0', expected: 'Even', isHidden: true },
      { input: '-7', expected: 'Odd', isHidden: true },
    ],
    examples: [
      { input: '8', output: 'Even', explanation: '8 & 1 == 0' },
    ],
    constraints: '-10^9 <= n <= 10^9',
    xpReward: 85,
    coinReward: 20,
  },

  // Stage 2: Control Structures & Loops
  {
    title: 'Sum of Natural Numbers',
    description: 'Read a positive integer `n` from standard input. Compute the sum of the first `n` natural numbers (`1 + 2 + ... + n`) and print the result.',
    language: 'cpp',
    topic: 'Control Structures',
    learningStage: 2,
    stageName: 'Control Structures & Loops',
    order: 5,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '5', expected: '15', isHidden: false },
      { input: '100', expected: '5050', isHidden: false },
      { input: '1', expected: '1', isHidden: true },
      { input: '1000', expected: '500500', isHidden: true },
    ],
    examples: [
      { input: '5', output: '15', explanation: '1 + 2 + 3 + 4 + 5 = 15' },
    ],
    constraints: '1 <= n <= 10^6',
    xpReward: 95,
    coinReward: 25,
  },
  {
    title: 'Print Number Range',
    description: 'Read two integers `start` and `end` from standard input. Print all integers from `start` to `end` (inclusive) on a single line separated by spaces.',
    language: 'cpp',
    topic: 'Control Structures',
    learningStage: 2,
    stageName: 'Control Structures & Loops',
    order: 6,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '3 7', expected: '3 4 5 6 7', isHidden: false },
      { input: '10 10', expected: '10', isHidden: false },
      { input: '-2 2', expected: '-2 -1 0 1 2', isHidden: true },
    ],
    examples: [
      { input: '3 7', output: '3 4 5 6 7', explanation: 'Range printed.' },
    ],
    constraints: 'start <= end, range <= 1000',
    xpReward: 95,
    coinReward: 25,
  },
  {
    title: 'Fibonacci Sequence in C++',
    description: 'Read integer `n` from standard input. Compute the `n`-th Fibonacci number where `F(0)=0`, `F(1)=1`, and print the answer.',
    language: 'cpp',
    topic: 'Control Structures',
    learningStage: 2,
    stageName: 'Control Structures & Loops',
    order: 7,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '7', expected: '13', isHidden: false },
      { input: '0', expected: '0', isHidden: false },
      { input: '12', expected: '144', isHidden: true },
    ],
    examples: [
      { input: '7', output: '13', explanation: 'F(7) = 13' },
    ],
    constraints: '0 <= n <= 45',
    xpReward: 100,
    coinReward: 25,
  },
  {
    title: 'Prime Number Verification in C++',
    description: 'Read an integer `n` from standard input. Print `"true"` if prime, or `"false"` if not.',
    language: 'cpp',
    topic: 'Control Structures',
    learningStage: 2,
    stageName: 'Control Structures & Loops',
    order: 8,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '29', expected: 'true', isHidden: false },
      { input: '1', expected: 'false', isHidden: false },
      { input: '49', expected: 'false', isHidden: true },
      { input: '2', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: '29', output: 'true', explanation: '29 is prime.' },
    ],
    constraints: '1 <= n <= 10^9',
    xpReward: 105,
    coinReward: 25,
  },

  // Stage 3: Functions & Pointers/References
  {
    title: 'Swap Two Values by Reference',
    description: 'Write a C++ function `void swap(int &a, int &b)`. Read two integers `a` and `b`, call `swap`, and print the swapped values formatted as `"a: X, b: Y"`.',
    language: 'cpp',
    topic: 'Functions & References',
    learningStage: 3,
    stageName: 'Functions & References',
    order: 9,
    difficulty: 'easy',
    category: 'functions',
    testCases: [
      { input: '10 20', expected: 'a: 20, b: 10', isHidden: false },
      { input: '5 5', expected: 'a: 5, b: 5', isHidden: false },
      { input: '-3 9', expected: 'a: 9, b: -3', isHidden: true },
    ],
    examples: [
      { input: '10 20', output: 'a: 20, b: 10', explanation: 'Values swapped using references.' },
    ],
    constraints: 'Values in standard integer range.',
    xpReward: 110,
    coinReward: 25,
  },
  {
    title: 'Pointer Array Sum',
    description: 'Read an integer `n` followed by `n` integers. Using pointer arithmetic `*(ptr + i)`, calculate the sum of the array and print the result.',
    language: 'cpp',
    topic: 'Functions & References',
    learningStage: 3,
    stageName: 'Functions & References',
    order: 10,
    difficulty: 'easy',
    category: 'pointers',
    testCases: [
      { input: '5\n1 2 3 4 5', expected: '15', isHidden: false },
      { input: '3\n10 20 30', expected: '60', isHidden: false },
      { input: '1\n42', expected: '42', isHidden: true },
    ],
    examples: [
      { input: '5\n1 2 3 4 5', output: '15', explanation: 'Sum calculated through pointers.' },
    ],
    constraints: '1 <= n <= 10^5',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Greatest Common Divisor (C++ Function)',
    description: 'Implement a recursive GCD function `int gcd(int a, int b)`. Read two integers from input and print their GCD.',
    language: 'cpp',
    topic: 'Functions & References',
    learningStage: 3,
    stageName: 'Functions & References',
    order: 11,
    difficulty: 'easy',
    category: 'functions',
    testCases: [
      { input: '56 98', expected: '14', isHidden: false },
      { input: '17 31', expected: '1', isHidden: false },
      { input: '270 192', expected: '6', isHidden: true },
    ],
    examples: [
      { input: '56 98', output: '14', explanation: 'GCD of 56 and 98 is 14.' },
    ],
    constraints: '1 <= a, b <= 10^9',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Pass Vector by Const Reference',
    description: 'Read a JSON array of integers. Pass the vector by `const std::vector<int>&` to a function that finds the maximum value and prints `"Max: X"`.',
    language: 'cpp',
    topic: 'Functions & References',
    learningStage: 3,
    stageName: 'Functions & References',
    order: 12,
    difficulty: 'easy',
    category: 'functions',
    testCases: [
      { input: '[3, 19, 4, 8, 12]', expected: 'Max: 19', isHidden: false },
      { input: '[-5, -2, -10]', expected: 'Max: -2', isHidden: false },
    ],
    examples: [
      { input: '[3, 19, 4, 8, 12]', output: 'Max: 19', explanation: '19 is maximum.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 120,
    coinReward: 30,
  },

  // Stage 4: Arrays & C-Strings
  {
    title: 'Array Min and Max Scan',
    description: 'Read a JSON array of integers from standard input. Find the minimum and maximum numbers and print `"Min: min, Max: max"`.',
    language: 'cpp',
    topic: 'Arrays & Strings',
    learningStage: 4,
    stageName: 'Arrays & Strings in C++',
    order: 13,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[12, 45, 2, 89, 34]', expected: 'Min: 2, Max: 89', isHidden: false },
      { input: '[-10, 0, 10]', expected: 'Min: -10, Max: 10', isHidden: false },
      { input: '[7]', expected: 'Min: 7, Max: 7', isHidden: true },
    ],
    examples: [
      { input: '[12, 45, 2, 89, 34]', output: 'Min: 2, Max: 89', explanation: '2 is min, 89 is max.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Reverse String in Place (Two Pointers)',
    description: 'Read a string from standard input. Reverse it in place using two pointers (`left` and `right`) and print the reversed string.',
    language: 'cpp',
    topic: 'Arrays & Strings',
    learningStage: 4,
    stageName: 'Arrays & Strings in C++',
    order: 14,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'algorithm', expected: 'mhtirogla', isHidden: false },
      { input: 'cpp', expected: 'ppc', isHidden: false },
      { input: 'radar', expected: 'radar', isHidden: true },
    ],
    examples: [
      { input: 'algorithm', output: 'mhtirogla', explanation: 'In-place two-pointer swap.' },
    ],
    constraints: '1 <= length <= 10^5',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Count Vowels in String (C++)',
    description: 'Read a string from standard input. Count and print the total number of vowels (A, E, I, O, U, case-insensitive).',
    language: 'cpp',
    topic: 'Arrays & Strings',
    learningStage: 4,
    stageName: 'Arrays & Strings in C++',
    order: 15,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'C++ Programming', expected: '3', isHidden: false },
      { input: 'QuestBoard', expected: '4', isHidden: false },
      { input: 'rhythm', expected: '0', isHidden: true },
    ],
    examples: [
      { input: 'C++ Programming', output: '3', explanation: 'o, a, i are vowels (3 total).' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 120,
    coinReward: 30,
  },
  {
    title: 'String Stream Word Parser',
    description: 'Read a line containing space-separated words using `std::stringstream`. Count and print the number of words.',
    language: 'cpp',
    topic: 'Arrays & Strings',
    learningStage: 4,
    stageName: 'Arrays & Strings in C++',
    order: 16,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'Fast efficient modern C++ development', expected: '5', isHidden: false },
      { input: 'QuestBoard', expected: '1', isHidden: false },
      { input: 'a b c d e f', expected: '6', isHidden: true },
    ],
    examples: [
      { input: 'Fast efficient modern C++ development', output: '5', explanation: '5 words.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 130,
    coinReward: 35,
  },

  // Stage 5: STL Vectors & Pairs
  {
    title: 'Vector Push Back & Sum',
    description: 'Read a JSON array of integers into a `std::vector<int>`. Calculate and print the sum of all elements.',
    language: 'cpp',
    topic: 'STL Vectors & Pairs',
    learningStage: 5,
    stageName: 'STL Vectors & Pairs',
    order: 17,
    difficulty: 'easy',
    category: 'stl',
    testCases: [
      { input: '[1, 2, 3, 4, 5]', expected: '15', isHidden: false },
      { input: '[-10, 20, 30]', expected: '40', isHidden: false },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5]', output: '15', explanation: 'Vector accumulated.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 130,
    coinReward: 30,
  },
  {
    title: 'Filter Even Numbers into Vector',
    description: 'Read a JSON array of integers. Filter out odd numbers, keeping only even numbers in a new vector. Print as a JSON array.',
    language: 'cpp',
    topic: 'STL Vectors & Pairs',
    learningStage: 5,
    stageName: 'STL Vectors & Pairs',
    order: 18,
    difficulty: 'easy',
    category: 'stl',
    testCases: [
      { input: '[1, 2, 3, 4, 5, 6]', expected: '[2,4,6]', isHidden: false },
      { input: '[1, 3, 5]', expected: '[]', isHidden: false },
      { input: '[0, 8, 12]', expected: '[0,8,12]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5, 6]', output: '[2,4,6]', explanation: 'Only even numbers preserved.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 135,
    coinReward: 35,
  },
  {
    title: 'Sort Vector of Pairs by Second Value',
    description: 'Read a JSON array of pairs `[[x1, y1], [x2, y2], ...]`. Sort the pairs in ascending order based on their second value `y`. Print the sorted JSON array.',
    language: 'cpp',
    topic: 'STL Vectors & Pairs',
    learningStage: 5,
    stageName: 'STL Vectors & Pairs',
    order: 19,
    difficulty: 'medium',
    category: 'stl',
    testCases: [
      { input: '[[1, 4], [2, 1], [3, 3]]', expected: '[[2,1],[3,3],[1,4]]', isHidden: false },
      { input: '[[5, 10], [2, 5]]', expected: '[[2,5],[5,10]]', isHidden: false },
    ],
    examples: [
      { input: '[[1, 4], [2, 1], [3, 3]]', output: '[[2,1],[3,3],[1,4]]', explanation: 'Sorted by y: 1 < 3 < 4.' },
    ],
    constraints: '1 <= pairs <= 10^4',
    xpReward: 145,
    coinReward: 35,
  },
  {
    title: 'Rotate Vector by K Elements',
    description: 'Read a JSON array of integers on line 1 and integer `k` on line 2. Rotate the vector right by `k` steps and print as a JSON array.',
    language: 'cpp',
    topic: 'STL Vectors & Pairs',
    learningStage: 5,
    stageName: 'STL Vectors & Pairs',
    order: 20,
    difficulty: 'medium',
    category: 'stl',
    testCases: [
      { input: '[1, 2, 3, 4, 5, 6, 7]\n3', expected: '[5,6,7,1,2,3,4]', isHidden: false },
      { input: '[-1, -100, 3, 99]\n2', expected: '[3,99,-1,-100]', isHidden: false },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5, 6, 7]\n3', output: '[5,6,7,1,2,3,4]', explanation: 'Elements rotated.' },
    ],
    constraints: '1 <= size <= 10^5, k >= 0',
    xpReward: 140,
    coinReward: 35,
  },

  // Stage 6: STL Maps & Sets
  {
    title: 'Word Count with std::map',
    description: 'Read a space-separated sentence from standard input. Use `std::map<std::string, int>` to count word frequencies and print sorted as `"word:count, word:count"`.',
    language: 'cpp',
    topic: 'STL Maps & Sets',
    learningStage: 6,
    stageName: 'STL Maps & Sets',
    order: 21,
    difficulty: 'medium',
    category: 'stl',
    testCases: [
      { input: 'cpp stl map stl cpp cpp', expected: 'cpp:3, map:1, stl:2', isHidden: false },
      { input: 'hello world', expected: 'hello:1, world:1', isHidden: false },
    ],
    examples: [
      { input: 'cpp stl map stl cpp cpp', output: 'cpp:3, map:1, stl:2', explanation: 'Lexicographical word frequency.' },
    ],
    constraints: 'Words <= 10^4',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Unique Elements with std::set',
    description: 'Read a JSON array of integers. Insert all elements into a `std::set<int>` and print the deduplicated sorted numbers as a JSON array.',
    language: 'cpp',
    topic: 'STL Maps & Sets',
    learningStage: 6,
    stageName: 'STL Maps & Sets',
    order: 22,
    difficulty: 'easy',
    category: 'stl',
    testCases: [
      { input: '[5, 2, 8, 2, 5, 1, 9]', expected: '[1,2,5,8,9]', isHidden: false },
      { input: '[10, 10, 10]', expected: '[10]', isHidden: false },
    ],
    examples: [
      { input: '[5, 2, 8, 2, 5, 1, 9]', output: '[1,2,5,8,9]', explanation: 'Unique sorted set.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 135,
    coinReward: 35,
  },
  {
    title: 'Two Sum with std::unordered_map',
    description: 'Given a JSON array of integers on line 1 and integer `target` on line 2, find the two indices using `std::unordered_map`. Print as a JSON array `[i, j]`.',
    language: 'cpp',
    topic: 'STL Maps & Sets',
    learningStage: 6,
    stageName: 'STL Maps & Sets',
    order: 23,
    difficulty: 'medium',
    category: 'stl',
    testCases: [
      { input: '[2, 7, 11, 15]\n9', expected: '[0,1]', isHidden: false },
      { input: '[3, 2, 4]\n6', expected: '[1,2]', isHidden: false },
      { input: '[3, 3]\n6', expected: '[0,1]', isHidden: true },
    ],
    examples: [
      { input: '[2, 7, 11, 15]\n9', output: '[0,1]', explanation: 'Indices 0 and 1 sum to 9.' },
    ],
    constraints: '2 <= size <= 10^5',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Set Intersection (std::set)',
    description: 'Read two JSON arrays on lines 1 and 2. Output the sorted common unique elements as a JSON array.',
    language: 'cpp',
    topic: 'STL Maps & Sets',
    learningStage: 6,
    stageName: 'STL Maps & Sets',
    order: 24,
    difficulty: 'easy',
    category: 'stl',
    testCases: [
      { input: '[1, 2, 2, 1]\n[2, 2]', expected: '[2]', isHidden: false },
      { input: '[4, 9, 5]\n[9, 4, 9, 8, 4]', expected: '[4,9]', isHidden: false },
    ],
    examples: [
      { input: '[1, 2, 2, 1]\n[2, 2]', output: '[2]', explanation: 'Unique common element is 2.' },
    ],
    constraints: '1 <= size <= 10^4',
    xpReward: 135,
    coinReward: 35,
  },

  // Stage 7: OOP in C++ (Classes & Structs)
  {
    title: 'Rectangle Struct with Methods',
    description: 'Define a `struct Rectangle` with `width` and `height`. Read two integers `w` and `h` and print `"Area: A, Perimeter: P"`.',
    language: 'cpp',
    topic: 'OOP in C++',
    learningStage: 7,
    stageName: 'OOP & Structs in C++',
    order: 25,
    difficulty: 'easy',
    category: 'oop',
    testCases: [
      { input: '6 8', expected: 'Area: 48, Perimeter: 28', isHidden: false },
      { input: '10 10', expected: 'Area: 100, Perimeter: 40', isHidden: false },
    ],
    examples: [
      { input: '6 8', output: 'Area: 48, Perimeter: 28', explanation: 'Area = 48, Perimeter = 28.' },
    ],
    constraints: '1 <= w, h <= 10^5',
    xpReward: 130,
    coinReward: 30,
  },
  {
    title: 'Complex Number Addition (Operator +)',
    description: 'Define a `Complex` class with `real` and `imag`. Read `r1 i1 r2 i2` representing two complex numbers. Add them and print `"Result: R+Ii"` (e.g. `"Result: 5+7i"`).',
    language: 'cpp',
    topic: 'OOP in C++',
    learningStage: 7,
    stageName: 'OOP & Structs in C++',
    order: 26,
    difficulty: 'medium',
    category: 'oop',
    testCases: [
      { input: '2 3 3 4', expected: 'Result: 5+7i', isHidden: false },
      { input: '1 2 4 5', expected: 'Result: 5+7i', isHidden: false },
      { input: '0 5 10 2', expected: 'Result: 10+7i', isHidden: true },
    ],
    examples: [
      { input: '2 3 3 4', output: 'Result: 5+7i', explanation: '(2+3i) + (3+4i) = 5+7i.' },
    ],
    constraints: 'Integers in range -1000 to 1000',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Custom Stack Class with Array',
    description: 'Implement a stack class with `push` and `pop`. Read operations `push X`, `pop` and print the popped items or `"Empty"`. When all done, print `"Stack Size: S"`.',
    language: 'cpp',
    topic: 'OOP in C++',
    learningStage: 7,
    stageName: 'OOP & Structs in C++',
    order: 27,
    difficulty: 'medium',
    category: 'oop',
    testCases: [
      { input: 'push 10\npush 20\npop\npush 30', expected: 'Popped: 20\nStack Size: 2', isHidden: false },
      { input: 'push 5\npop\npop', expected: 'Popped: 5\nEmpty\nStack Size: 0', isHidden: false },
    ],
    examples: [
      { input: 'push 10\npush 20\npop\npush 30', output: 'Popped: 20\nStack Size: 2', explanation: 'LIFO order maintained.' },
    ],
    constraints: '1 <= ops <= 100',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Valid Parentheses with std::stack',
    description: 'Read a string of brackets `()[]{}` from standard input. Use `std::stack<char>` to verify if properly closed. Print `"true"` or `"false"`.',
    language: 'cpp',
    topic: 'OOP in C++',
    learningStage: 7,
    stageName: 'OOP & Structs in C++',
    order: 28,
    difficulty: 'medium',
    category: 'stacks',
    testCases: [
      { input: '()[]{}', expected: 'true', isHidden: false },
      { input: '(]', expected: 'false', isHidden: false },
      { input: '{[]}', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: '()[]{}', output: 'true', explanation: 'Valid stack bracket matching.' },
    ],
    constraints: '1 <= len <= 10^4',
    xpReward: 155,
    coinReward: 40,
  },

  // Stage 8: Problem Solving & DSA in C++
  {
    title: 'Binary Search Implementation in C++',
    description: 'Read a sorted JSON integer array on line 1 and integer `target` on line 2. Find and print the index of `target`, or `-1` if not found.',
    language: 'cpp',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 29,
    difficulty: 'easy',
    category: 'searching',
    testCases: [
      { input: '[-1, 0, 3, 5, 9, 12]\n9', expected: '4', isHidden: false },
      { input: '[-1, 0, 3, 5, 9, 12]\n2', expected: '-1', isHidden: false },
      { input: '[1, 2, 3, 4, 5, 6, 7]\n6', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '[-1, 0, 3, 5, 9, 12]\n9', output: '4', explanation: '9 is at index 4.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Merge Two Sorted Vectors',
    description: 'Read two sorted JSON arrays on line 1 and line 2. Merge them into a single sorted JSON array in O(n+m) time.',
    language: 'cpp',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 30,
    difficulty: 'medium',
    category: 'sorting',
    testCases: [
      { input: '[1, 2, 4]\n[1, 3, 4]', expected: '[1,1,2,3,4,4]', isHidden: false },
      { input: '[]\n[0]', expected: '[0]', isHidden: false },
      { input: '[2, 5, 8]\n[1, 3, 7, 9]', expected: '[1,2,3,5,7,8,9]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 4]\n[1, 3, 4]', output: '[1,1,2,3,4,4]', explanation: 'Merged sorted arrays.' },
    ],
    constraints: '1 <= n+m <= 10^5',
    xpReward: 165,
    coinReward: 45,
  },
  {
    title: 'Maximum Subarray (Kadane in C++)',
    description: 'Given a JSON array of integers, find the contiguous subarray with the largest sum and print its sum.',
    language: 'cpp',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 31,
    difficulty: 'medium',
    category: 'dynamic-programming',
    testCases: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', expected: '6', isHidden: false },
      { input: '[5, 4, -1, 7, 8]', expected: '23', isHidden: false },
      { input: '[-1]', expected: '-1', isHidden: true },
    ],
    examples: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', output: '6', explanation: 'Max subarray sum is 6.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 175,
    coinReward: 50,
  },
  {
    title: 'Container With Most Water (C++)',
    description: 'Given a JSON array of non-negative integers representing vertical line heights, find two lines that together with the x-axis form a container that contains the most water. Print the maximum water area.',
    language: 'cpp',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 32,
    difficulty: 'medium',
    category: 'two-pointers',
    testCases: [
      { input: '[1, 8, 6, 2, 5, 4, 8, 3, 7]', expected: '49', isHidden: false },
      { input: '[1, 1]', expected: '1', isHidden: false },
      { input: '[4, 3, 2, 1, 4]', expected: '16', isHidden: true },
    ],
    examples: [
      { input: '[1, 8, 6, 2, 5, 4, 8, 3, 7]', output: '49', explanation: 'Max area is 49.' },
    ],
    constraints: '2 <= len <= 10^5',
    xpReward: 185,
    coinReward: 50,
  },
];
