export const javascriptChallenges = [
  // Stage 1: JS Fundamentals & Variables
  {
    title: 'Hello JavaScript',
    description: 'Write a JavaScript (Node.js) program that prints `"Hello, JavaScript!"` to standard output.',
    language: 'javascript',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'JS Fundamentals & Syntax',
    order: 1,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '', expected: 'Hello, JavaScript!', isHidden: false },
      { input: 'run', expected: 'Hello, JavaScript!', isHidden: true },
    ],
    examples: [
      { input: '(none)', output: 'Hello, JavaScript!', explanation: 'The program logs the greeting string to console.' },
    ],
    constraints: 'Must output exact casing.',
    xpReward: 75,
    coinReward: 20,
  },
  {
    title: 'Area of a Rectangle',
    description: 'Read two numbers (width and height) from standard input separated by whitespace or newlines. Calculate and print the area of the rectangle.',
    language: 'javascript',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'JS Fundamentals & Syntax',
    order: 2,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '5 8', expected: '40', isHidden: false },
      { input: '12\n10', expected: '120', isHidden: false },
      { input: '3.5 2', expected: '7', isHidden: true },
      { input: '25 25', expected: '625', isHidden: true },
    ],
    examples: [
      { input: '5 8', output: '40', explanation: '5 * 8 = 40' },
    ],
    constraints: '1 <= width, height <= 10^5',
    xpReward: 80,
    coinReward: 20,
  },
  {
    title: 'Leap Year Checker',
    description: 'Read a year integer from standard input. A year is a leap year if it is divisible by 4, except end-of-century years which must be divisible by 400. Print `"true"` if it is a leap year, otherwise `"false"`.',
    language: 'javascript',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'JS Fundamentals & Syntax',
    order: 3,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '2024', expected: 'true', isHidden: false },
      { input: '1900', expected: 'false', isHidden: false },
      { input: '2000', expected: 'true', isHidden: true },
      { input: '2023', expected: 'false', isHidden: true },
    ],
    examples: [
      { input: '2024', output: 'true', explanation: '2024 is divisible by 4 and not a century year.' },
    ],
    constraints: '1 <= year <= 9999',
    xpReward: 85,
    coinReward: 20,
  },
  {
    title: 'Strict Type Coercion Handler',
    description: 'Read a line containing two space-separated tokens from standard input. Determine if they are loosely equal (`==`) and strictly equal (`===`). Print `"Loose: true/false, Strict: true/false"`. (Use JSON parsing if tokens are valid JSON values).',
    language: 'javascript',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'JS Fundamentals & Syntax',
    order: 4,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '0 false', expected: 'Loose: true, Strict: false', isHidden: false },
      { input: '5 5', expected: 'Loose: true, Strict: true', isHidden: false },
      { input: '"5" 5', expected: 'Loose: true, Strict: false', isHidden: true },
    ],
    examples: [
      { input: '0 false', output: 'Loose: true, Strict: false', explanation: '0 == false is true, but 0 === false is false.' },
    ],
    constraints: 'Input contains two tokens.',
    xpReward: 90,
    coinReward: 20,
  },

  // Stage 2: Control Flow & Conditionals
  {
    title: 'Grade Evaluator',
    description: 'Read a numeric score (0-100) from standard input. Print `"A"` for >= 90, `"B"` for >= 80, `"C"` for >= 70, `"D"` for >= 60, and `"F"` for < 60.',
    language: 'javascript',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 5,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '95', expected: 'A', isHidden: false },
      { input: '82', expected: 'B', isHidden: false },
      { input: '68', expected: 'D', isHidden: true },
      { input: '45', expected: 'F', isHidden: true },
    ],
    examples: [
      { input: '95', output: 'A', explanation: '95 >= 90 yields grade A.' },
    ],
    constraints: '0 <= score <= 100',
    xpReward: 95,
    coinReward: 25,
  },
  {
    title: 'Sum of Multiples of 3 and 5',
    description: 'Read an integer `n` from standard input. Calculate the sum of all natural numbers below `n` that are multiples of 3 or 5 and print the sum.',
    language: 'javascript',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 6,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '10', expected: '23', isHidden: false },
      { input: '20', expected: '78', isHidden: false },
      { input: '100', expected: '2318', isHidden: true },
    ],
    examples: [
      { input: '10', output: '23', explanation: 'Multiples below 10 are 3, 5, 6, 9. Sum = 23.' },
    ],
    constraints: '1 <= n <= 10^5',
    xpReward: 100,
    coinReward: 25,
  },
  {
    title: 'Prime Number Checker',
    description: 'Read an integer `n` from standard input. Print `"true"` if `n` is a prime number, otherwise `"false"`.',
    language: 'javascript',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 7,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '13', expected: 'true', isHidden: false },
      { input: '1', expected: 'false', isHidden: false },
      { input: '25', expected: 'false', isHidden: true },
      { input: '97', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: '13', output: 'true', explanation: '13 has no divisors other than 1 and 13.' },
    ],
    constraints: '1 <= n <= 10^7',
    xpReward: 105,
    coinReward: 25,
  },
  {
    title: 'Count Evens in Loop',
    description: 'Read a JSON array of integers from standard input. Using a loop, count how many numbers are even and print the count.',
    language: 'javascript',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 8,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '[1, 2, 3, 4, 5, 6]', expected: '3', isHidden: false },
      { input: '[1, 3, 5, 7]', expected: '0', isHidden: false },
      { input: '[0, 2, 4, 8, 10]', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5, 6]', output: '3', explanation: '2, 4, 6 are even (3 numbers).' },
    ],
    constraints: '1 <= array length <= 10^4',
    xpReward: 100,
    coinReward: 25,
  },

  // Stage 3: Strings & Template Literals
  {
    title: 'Reverse Words in a Sentence',
    description: 'Given a sentence from standard input, reverse the order of the words while keeping individual words intact. Print the result.',
    language: 'javascript',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Template Literals',
    order: 9,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'the sky is blue', expected: 'blue is sky the', isHidden: false },
      { input: 'hello world', expected: 'world hello', isHidden: false },
      { input: 'coding academy questboard', expected: 'questboard academy coding', isHidden: true },
    ],
    examples: [
      { input: 'the sky is blue', output: 'blue is sky the', explanation: 'Words reversed in sentence sequence.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 110,
    coinReward: 25,
  },
  {
    title: 'Mask Credit Card Number',
    description: 'Read a credit card string from standard input. Mask all characters with `#` except the last 4 characters. If the string has 4 or fewer characters, return it unchanged. Print the masked string.',
    language: 'javascript',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Template Literals',
    order: 10,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: '4532789123456789', expected: '############6789', isHidden: false },
      { input: '1234', expected: '1234', isHidden: false },
      { input: '987654321', expected: '#####4321', isHidden: true },
    ],
    examples: [
      { input: '4532789123456789', output: '############6789', explanation: 'First 12 digits replaced by #, last 4 kept.' },
    ],
    constraints: '1 <= length <= 30',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Count Character Frequency',
    description: 'Read a string from standard input. Count the frequency of each lowercase character and print them in alphabetical order as `"a:count, b:count"`.',
    language: 'javascript',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Template Literals',
    order: 11,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'javascript', expected: 'a:2, c:1, i:1, j:1, p:1, r:1, s:1, t:1, v:1', isHidden: false },
      { input: 'banana', expected: 'a:3, b:1, n:2', isHidden: false },
      { input: 'quest', expected: 'e:1, q:1, s:1, t:1, u:1', isHidden: true },
    ],
    examples: [
      { input: 'banana', output: 'a:3, b:1, n:2', explanation: 'Sorted alphabetical character counts.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 120,
    coinReward: 30,
  },
  {
    title: 'Truncate String with Ellipsis',
    description: 'Read a string on line 1 and a maximum length `num` on line 2. If the string is longer than `num`, truncate it and append `...` to the end so total length equals `num + 3`. Otherwise print the original string.',
    language: 'javascript',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Template Literals',
    order: 12,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'A-tisket a-tasket A green and yellow basket\n8', expected: 'A-tisket...', isHidden: false },
      { input: 'Peter Piper\n20', expected: 'Peter Piper', isHidden: false },
      { input: 'QuestBoard\n5', expected: 'Quest...', isHidden: true },
    ],
    examples: [
      { input: 'A-tisket a-tasket A green and yellow basket\n8', output: 'A-tisket...', explanation: 'Truncated at 8 chars with ellipsis.' },
    ],
    constraints: '1 <= length <= 1000, num >= 1',
    xpReward: 115,
    coinReward: 30,
  },

  // Stage 4: Arrays & Modern Array Methods
  {
    title: 'Double Array Values with Map',
    description: 'Read a JSON array of numbers from standard input. Use `Array.prototype.map` to double each value and print the resulting JSON array.',
    language: 'javascript',
    topic: 'Array Methods',
    learningStage: 4,
    stageName: 'Arrays & Functional Methods',
    order: 13,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[1, 2, 3, 4]', expected: '[2,4,6,8]', isHidden: false },
      { input: '[-5, 0, 10]', expected: '[-10,0,20]', isHidden: false },
      { input: '[100]', expected: '[200]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4]', output: '[2,4,6,8]', explanation: 'Each element multiplied by 2.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 120,
    coinReward: 30,
  },
  {
    title: 'Filter Positive Numbers',
    description: 'Read a JSON array of integers from standard input. Use `Array.prototype.filter` to keep only strictly positive numbers (> 0) and print the result as a JSON array.',
    language: 'javascript',
    topic: 'Array Methods',
    learningStage: 4,
    stageName: 'Arrays & Functional Methods',
    order: 14,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[-2, 5, 0, -1, 8, 12]', expected: '[5,8,12]', isHidden: false },
      { input: '[-1, -2, -3]', expected: '[]', isHidden: false },
      { input: '[1, 2, 3]', expected: '[1,2,3]', isHidden: true },
    ],
    examples: [
      { input: '[-2, 5, 0, -1, 8, 12]', output: '[5,8,12]', explanation: 'Only positive numbers preserved.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Array Accumulator with Reduce',
    description: 'Read a JSON array of numbers from standard input. Use `Array.prototype.reduce` to compute the product of all elements. If the array is empty, print `1`.',
    language: 'javascript',
    topic: 'Array Methods',
    learningStage: 4,
    stageName: 'Arrays & Functional Methods',
    order: 15,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[1, 2, 3, 4, 5]', expected: '120', isHidden: false },
      { input: '[10, -2, 3]', expected: '-60', isHidden: false },
      { input: '[]', expected: '1', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5]', output: '120', explanation: '1 * 2 * 3 * 4 * 5 = 120' },
    ],
    constraints: '0 <= length <= 20',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Find Longest Word in Sentence',
    description: 'Read a sentence from standard input. Find the longest word and print `"Word: word, Length: length"`. If there are ties, return the first one.',
    language: 'javascript',
    topic: 'Array Methods',
    learningStage: 4,
    stageName: 'Arrays & Functional Methods',
    order: 16,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'The quick brown fox jumped over the lazy dog', expected: 'Word: jumped, Length: 6', isHidden: false },
      { input: 'JavaScript algorithms rock', expected: 'Word: JavaScript, Length: 10', isHidden: false },
      { input: 'QuestBoard provides great paths', expected: 'Word: QuestBoard, Length: 10', isHidden: true },
    ],
    examples: [
      { input: 'The quick brown fox jumped over the lazy dog', output: 'Word: jumped, Length: 6', explanation: 'jumped is the longest with length 6.' },
    ],
    constraints: '1 <= words <= 1000',
    xpReward: 130,
    coinReward: 35,
  },

  // Stage 5: Objects & Destructuring
  {
    title: 'Object Property Count',
    description: 'Read a JSON object from standard input. Count and print the number of top-level keys in the object.',
    language: 'javascript',
    topic: 'Objects & ES6',
    learningStage: 5,
    stageName: 'Objects & ES6+ Features',
    order: 17,
    difficulty: 'easy',
    category: 'objects',
    testCases: [
      { input: '{"name": "Alice", "age": 25, "role": "admin"}', expected: '3', isHidden: false },
      { input: '{}', expected: '0', isHidden: false },
      { input: '{"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '{"name": "Alice", "age": 25, "role": "admin"}', output: '3', explanation: 'Object has 3 keys.' },
    ],
    constraints: 'Valid JSON object.',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Deep Merge Configuration Objects',
    description: 'Read two JSON objects from standard input (line 1 and line 2). Merge them such that keys from object 2 override keys in object 1. Print the merged result as a JSON string with keys in alphabetical order.',
    language: 'javascript',
    topic: 'Objects & ES6',
    learningStage: 5,
    stageName: 'Objects & ES6+ Features',
    order: 18,
    difficulty: 'medium',
    category: 'objects',
    testCases: [
      { input: '{"theme": "dark", "fontSize": 14}\n{"fontSize": 16, "showLineNumbers": true}', expected: '{"fontSize":16,"showLineNumbers":true,"theme":"dark"}', isHidden: false },
      { input: '{"a": 1, "b": 2}\n{"c": 3}', expected: '{"a":1,"b":2,"c":3}', isHidden: false },
    ],
    examples: [
      { input: '{"theme": "dark", "fontSize": 14}\n{"fontSize": 16, "showLineNumbers": true}', output: '{"fontSize":16,"showLineNumbers":true,"theme":"dark"}', explanation: 'fontSize updated to 16, showLineNumbers added.' },
    ],
    constraints: 'Objects depth = 1',
    xpReward: 135,
    coinReward: 35,
  },
  {
    title: 'Invert Key-Value Map',
    description: 'Read a JSON object whose values are strings or numbers. Invert the object so that the values become keys and the keys become values. Print the sorted JSON object.',
    language: 'javascript',
    topic: 'Objects & ES6',
    learningStage: 5,
    stageName: 'Objects & ES6+ Features',
    order: 19,
    difficulty: 'easy',
    category: 'objects',
    testCases: [
      { input: '{"a": "1", "b": "2", "c": "3"}', expected: '{"1":"a","2":"b","3":"c"}', isHidden: false },
      { input: '{"red": "#f00", "green": "#0f0"}', expected: '{"#0f0":"green","#f00":"red"}', isHidden: false },
    ],
    examples: [
      { input: '{"a": "1", "b": "2", "c": "3"}', output: '{"1":"a","2":"b","3":"c"}', explanation: 'Keys and values swapped.' },
    ],
    constraints: 'Values are unique strings/numbers.',
    xpReward: 130,
    coinReward: 35,
  },
  {
    title: 'Array of Objects Pluck and Filter',
    description: 'Read a JSON array of user objects on line 1 `[{"name":"A","age":20,"active":true},...]`. Filter only active users, extract their `name` property into an array, and print as a JSON array.',
    language: 'javascript',
    topic: 'Objects & ES6',
    learningStage: 5,
    stageName: 'Objects & ES6+ Features',
    order: 20,
    difficulty: 'medium',
    category: 'objects',
    testCases: [
      { input: '[{"name":"Alice","active":true},{"name":"Bob","active":false},{"name":"Charlie","active":true}]', expected: '["Alice","Charlie"]', isHidden: false },
      { input: '[{"name":"Dave","active":false}]', expected: '[]', isHidden: false },
    ],
    examples: [
      { input: '[{"name":"Alice","active":true},{"name":"Bob","active":false}]', output: '["Alice"]', explanation: 'Only Alice is active.' },
    ],
    constraints: '1 <= array length <= 1000',
    xpReward: 135,
    coinReward: 35,
  },

  // Stage 6: Functions, Closures & Advanced ES6
  {
    title: 'Memoize Function Simulator',
    description: 'Simulate a memoized square function. Read a JSON array of numbers representing sequential calls. Print the total count of cache hits formatted as `"Computed: X, Cache Hits: Y"`.',
    language: 'javascript',
    topic: 'Closures & Functions',
    learningStage: 6,
    stageName: 'Closures & Function Mastery',
    order: 21,
    difficulty: 'medium',
    category: 'closures',
    testCases: [
      { input: '[2, 3, 2, 4, 3, 2]', expected: 'Computed: 3, Cache Hits: 3', isHidden: false },
      { input: '[1, 2, 3, 4]', expected: 'Computed: 4, Cache Hits: 0', isHidden: false },
      { input: '[5, 5, 5, 5, 5]', expected: 'Computed: 1, Cache Hits: 4', isHidden: true },
    ],
    examples: [
      { input: '[2, 3, 2, 4, 3, 2]', output: 'Computed: 3, Cache Hits: 3', explanation: '2 and 3 called multiple times reused from cache.' },
    ],
    constraints: '1 <= calls <= 10^4',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Curried Adder Implementation',
    description: 'Implement a currying evaluator. Read a JSON array of numbers `[a, b, c, ...]` from standard input and evaluate `add(a)(b)(c)...` to return the total sum.',
    language: 'javascript',
    topic: 'Closures & Functions',
    learningStage: 6,
    stageName: 'Closures & Function Mastery',
    order: 22,
    difficulty: 'medium',
    category: 'functions',
    testCases: [
      { input: '[1, 2, 3, 4]', expected: '10', isHidden: false },
      { input: '[10, 20]', expected: '30', isHidden: false },
      { input: '[5]', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4]', output: '10', explanation: '1 + 2 + 3 + 4 = 10' },
    ],
    constraints: '1 <= array length <= 100',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Custom Deep Clone',
    description: 'Read a nested JSON object or array from standard input. Create a deep clone and print the cloned JSON structure.',
    language: 'javascript',
    topic: 'Closures & Functions',
    learningStage: 6,
    stageName: 'Closures & Function Mastery',
    order: 23,
    difficulty: 'medium',
    category: 'objects',
    testCases: [
      { input: '{"user":{"profile":{"age":30},"roles":["admin","editor"]}}', expected: '{"user":{"profile":{"age":30},"roles":["admin","editor"]}}', isHidden: false },
      { input: '[1, [2, [3]]]', expected: '[1,[2,[3]]]', isHidden: false },
    ],
    examples: [
      { input: '{"a":{"b":1}}', output: '{"a":{"b":1}}', explanation: 'Structure deep cloned.' },
    ],
    constraints: 'Valid JSON input.',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Function Composition Pipeline',
    description: 'Given a starting number `x` on line 1 and a series of operations on line 2 (e.g. `double,add5,square`), evaluate the pipeline in left-to-right order where: `double` = `n*2`, `add5` = `n+5`, `square` = `n*n`, `sub3` = `n-3`. Print the final value.',
    language: 'javascript',
    topic: 'Closures & Functions',
    learningStage: 6,
    stageName: 'Closures & Function Mastery',
    order: 24,
    difficulty: 'medium',
    category: 'functions',
    testCases: [
      { input: '4\ndouble,add5,square', expected: '169', isHidden: false },
      { input: '10\nsub3,double', expected: '14', isHidden: false },
      { input: '2\nsquare,square,double', expected: '32', isHidden: true },
    ],
    examples: [
      { input: '4\ndouble,add5,square', output: '169', explanation: '4 * 2 = 8 -> 8 + 5 = 13 -> 13^2 = 169.' },
    ],
    constraints: '1 <= operations <= 10',
    xpReward: 150,
    coinReward: 40,
  },

  // Stage 7: Asynchronous JavaScript & Promises
  {
    title: 'Promise Chain Aggregator',
    description: 'Read a JSON array of step delays in ms `[10, 20, 30]`. Simulate chaining promises that resolve in sequential order and print `"All 3 steps resolved successfully"`.',
    language: 'javascript',
    topic: 'Async JavaScript',
    learningStage: 7,
    stageName: 'Async JS & Promises',
    order: 25,
    difficulty: 'medium',
    category: 'async',
    testCases: [
      { input: '[10, 20, 30]', expected: 'All 3 steps resolved successfully', isHidden: false },
      { input: '[5, 5]', expected: 'All 2 steps resolved successfully', isHidden: false },
      { input: '[1]', expected: 'All 1 steps resolved successfully', isHidden: true },
    ],
    examples: [
      { input: '[10, 20, 30]', output: 'All 3 steps resolved successfully', explanation: 'All steps resolved sequentially.' },
    ],
    constraints: 'Delays <= 100ms',
    xpReward: 150,
    coinReward: 45,
  },
  {
    title: 'Promise.all Simulation',
    description: 'Given a JSON array of numbers, simulate resolving each number multiplied by 10 concurrently using `Promise.all`. Print the resulting array as JSON.',
    language: 'javascript',
    topic: 'Async JavaScript',
    learningStage: 7,
    stageName: 'Async JS & Promises',
    order: 26,
    difficulty: 'medium',
    category: 'async',
    testCases: [
      { input: '[1, 2, 3, 4]', expected: '[10,20,30,40]', isHidden: false },
      { input: '[5, 0, -2]', expected: '[50,0,-20]', isHidden: false },
    ],
    examples: [
      { input: '[1, 2, 3, 4]', output: '[10,20,30,40]', explanation: 'Concurrent promise resolutions.' },
    ],
    constraints: '1 <= array length <= 100',
    xpReward: 155,
    coinReward: 45,
  },
  {
    title: 'Debounce Call Counter',
    description: 'Read a stream of event timestamps in ms `[10, 20, 50, 150, 160, 300]` on line 1 and a debounce delay `threshold` (e.g. `50`) on line 2. Count how many actual calls execute after debounce cooldowns. Print the executed count.',
    language: 'javascript',
    topic: 'Async JavaScript',
    learningStage: 7,
    stageName: 'Async JS & Promises',
    order: 27,
    difficulty: 'medium',
    category: 'async',
    testCases: [
      { input: '[10, 20, 50, 150, 160, 300]\n50', expected: '3', isHidden: false },
      { input: '[0, 10, 20, 30, 40]\n50', expected: '1', isHidden: false },
    ],
    examples: [
      { input: '[10, 20, 50, 150, 160, 300]\n50', output: '3', explanation: 'Bursts resolve into 3 executed actions.' },
    ],
    constraints: 'Timestamps sorted ascending.',
    xpReward: 160,
    coinReward: 45,
  },
  {
    title: 'Async Retry with Exponential Backoff Simulator',
    description: 'Read maximum attempts `maxRetries` (e.g. `3`) on line 1 and a failure count `fails` (e.g. `2`) on line 2. If `fails < maxRetries`, print `"Success after X retries"`. Otherwise print `"Failed after max retries"`.',
    language: 'javascript',
    topic: 'Async JavaScript',
    learningStage: 7,
    stageName: 'Async JS & Promises',
    order: 28,
    difficulty: 'medium',
    category: 'async',
    testCases: [
      { input: '3\n2', expected: 'Success after 2 retries', isHidden: false },
      { input: '3\n4', expected: 'Failed after max retries', isHidden: false },
      { input: '5\n0', expected: 'Success after 0 retries', isHidden: true },
    ],
    examples: [
      { input: '3\n2', output: 'Success after 2 retries', explanation: '2 failures then succeeds within limit of 3.' },
    ],
    constraints: '1 <= maxRetries <= 10',
    xpReward: 160,
    coinReward: 45,
  },

  // Stage 8: Problem Solving & DSA in JavaScript
  {
    title: 'Two Sum in JavaScript (Map)',
    description: 'Given a JSON array of integers on line 1 and integer `target` on line 2, return the 0-based indices of the two numbers that add up to `target` as a JSON array using a JavaScript `Map`.',
    language: 'javascript',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 29,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[2, 7, 11, 15]\n9', expected: '[0,1]', isHidden: false },
      { input: '[3, 2, 4]\n6', expected: '[1,2]', isHidden: false },
      { input: '[3, 3]\n6', expected: '[0,1]', isHidden: true },
    ],
    examples: [
      { input: '[2, 7, 11, 15]\n9', output: '[0,1]', explanation: '2 + 7 = 9 at indices 0 and 1.' },
    ],
    constraints: '2 <= len <= 10^5',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Valid Anagram Check',
    description: 'Given two space-separated words from standard input, determine if the second word is an anagram of the first (same characters in different order). Print `"true"` or `"false"`.',
    language: 'javascript',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 30,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'anagram nagaram', expected: 'true', isHidden: false },
      { input: 'rat car', expected: 'false', isHidden: false },
      { input: 'listen silent', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: 'anagram nagaram', output: 'true', explanation: 'Contains same letter counts.' },
    ],
    constraints: '1 <= length <= 5 * 10^4',
    xpReward: 140,
    coinReward: 35,
  },
  {
    title: 'Top K Frequent Elements',
    description: 'Read a JSON array of numbers on line 1 and integer `k` on line 2. Return the `k` most frequent elements sorted in ascending order as a JSON array.',
    language: 'javascript',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 31,
    difficulty: 'medium',
    category: 'arrays',
    testCases: [
      { input: '[1, 1, 1, 2, 2, 3]\n2', expected: '[1,2]', isHidden: false },
      { input: '[1]\n1', expected: '[1]', isHidden: false },
      { input: '[4, 1, -1, 2, -1, 2, 3]\n2', expected: '[-1,2]', isHidden: true },
    ],
    examples: [
      { input: '[1, 1, 1, 2, 2, 3]\n2', output: '[1,2]', explanation: '1 occurs 3 times, 2 occurs 2 times.' },
    ],
    constraints: '1 <= k <= unique elements',
    xpReward: 175,
    coinReward: 50,
  },
  {
    title: 'Maximum Subarray (Kadane in JS)',
    description: 'Given a JSON array of integers, find the contiguous subarray with the largest sum and print its sum.',
    language: 'javascript',
    topic: 'Problem Solving & DSA',
    learningStage: 8,
    stageName: 'Problem Solving & DSA',
    order: 32,
    difficulty: 'medium',
    category: 'dynamic-programming',
    testCases: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', expected: '6', isHidden: false },
      { input: '[5, 4, -1, 7, 8]', expected: '23', isHidden: false },
      { input: '[-1]', expected: '-1', isHidden: true },
    ],
    examples: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', output: '6', explanation: 'Max sum subarray is [4, -1, 2, 1] = 6.' },
    ],
    constraints: '1 <= length <= 10^5',
    xpReward: 180,
    coinReward: 50,
  },
];
