export const javaChallenges = [
  // Stage 1: Java Fundamentals & Syntax
  {
    title: 'Hello Java Realm',
    description: 'Write a Java program that prints `"Hello, Java!"` to standard output.',
    language: 'java',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Java Fundamentals',
    order: 1,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '', expected: 'Hello, Java!', isHidden: false },
      { input: 'start', expected: 'Hello, Java!', isHidden: true },
    ],
    examples: [
      { input: '(none)', output: 'Hello, Java!', explanation: 'System.out.println output.' },
    ],
    constraints: 'Exact casing and punctuation.',
    xpReward: 75,
    coinReward: 20,
  },
  {
    title: 'Sum of Two Integers',
    description: 'Read two integers from standard input using `Scanner` (or standard I/O) and print their sum.',
    language: 'java',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Java Fundamentals',
    order: 2,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '4 7', expected: '11', isHidden: false },
      { input: '20 35', expected: '55', isHidden: false },
      { input: '-15 30', expected: '15', isHidden: true },
    ],
    examples: [
      { input: '4 7', output: '11', explanation: '4 + 7 = 11' },
    ],
    constraints: '-10^6 <= a, b <= 10^6',
    xpReward: 80,
    coinReward: 20,
  },
  {
    title: 'Temperature Conversion (Celsius to Fahrenheit)',
    description: 'Read a double Celsius value from standard input. Convert to Fahrenheit using `(C * 9.0/5.0) + 32.0` and print formatted to 1 decimal place (e.g. `98.6`).',
    language: 'java',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Java Fundamentals',
    order: 3,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '0', expected: '32.0', isHidden: false },
      { input: '37', expected: '98.6', isHidden: false },
      { input: '100', expected: '212.0', isHidden: true },
    ],
    examples: [
      { input: '37', output: '98.6', explanation: '(37 * 9/5) + 32 = 98.6' },
    ],
    constraints: '-100.0 <= C <= 1000.0',
    xpReward: 85,
    coinReward: 20,
  },
  {
    title: 'Sign of a Number',
    description: 'Read an integer from standard input. Print `"Positive"` if > 0, `"Negative"` if < 0, and `"Zero"` if == 0.',
    language: 'java',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Java Fundamentals',
    order: 4,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '15', expected: 'Positive', isHidden: false },
      { input: '-8', expected: 'Negative', isHidden: false },
      { input: '0', expected: 'Zero', isHidden: true },
    ],
    examples: [
      { input: '15', output: 'Positive', explanation: '15 is greater than 0.' },
    ],
    constraints: '-10^9 <= n <= 10^9',
    xpReward: 85,
    coinReward: 20,
  },

  // Stage 2: Control Flow & Loops
  {
    title: 'Count Multiples of N',
    description: 'Read two integers `N` and `Limit` from standard input. Count how many multiples of `N` exist between 1 and `Limit` (inclusive) and print the count.',
    language: 'java',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 5,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '3 20', expected: '6', isHidden: false },
      { input: '5 50', expected: '10', isHidden: false },
      { input: '7 10', expected: '1', isHidden: true },
    ],
    examples: [
      { input: '3 20', output: '6', explanation: 'Multiples: 3, 6, 9, 12, 15, 18 (6 total).' },
    ],
    constraints: '1 <= N, Limit <= 10^7',
    xpReward: 95,
    coinReward: 25,
  },
  {
    title: 'Factorial Calculation in Java',
    description: 'Read a non-negative integer `n` from standard input. Compute and print `n!`.',
    language: 'java',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 6,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '5', expected: '120', isHidden: false },
      { input: '0', expected: '1', isHidden: false },
      { input: '8', expected: '40320', isHidden: true },
    ],
    examples: [
      { input: '5', output: '120', explanation: '5! = 120' },
    ],
    constraints: '0 <= n <= 15',
    xpReward: 100,
    coinReward: 25,
  },
  {
    title: 'Reverse Integer Digits',
    description: 'Read a positive integer from standard input. Print the reversed number with leading zeroes stripped (e.g. 120 -> 21).',
    language: 'java',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 7,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '12345', expected: '54321', isHidden: false },
      { input: '120', expected: '21', isHidden: false },
      { input: '9000', expected: '9', isHidden: true },
    ],
    examples: [
      { input: '12345', output: '54321', explanation: 'Digits reversed.' },
    ],
    constraints: '1 <= n <= 10^9',
    xpReward: 100,
    coinReward: 25,
  },
  {
    title: 'Right-Angled Star Triangle',
    description: 'Read an integer `n` from standard input. Print a right-angled triangle of stars `*` with `n` rows, where row `i` has `i` stars.',
    language: 'java',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 8,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '3', expected: '*\n**\n***', isHidden: false },
      { input: '1', expected: '*', isHidden: false },
      { input: '4', expected: '*\n**\n***\n****', isHidden: true },
    ],
    examples: [
      { input: '3', output: '*\n**\n***', explanation: '3 rows of stars.' },
    ],
    constraints: '1 <= n <= 20',
    xpReward: 105,
    coinReward: 25,
  },

  // Stage 3: Strings & StringBuilder
  {
    title: 'Palindrome String Verification',
    description: 'Read a string from standard input. Check if it is a palindrome (case-insensitive alphanumeric only). Print `"true"` or `"false"`.',
    language: 'java',
    topic: 'Strings & StringBuilder',
    learningStage: 3,
    stageName: 'Strings & StringBuilder',
    order: 9,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'racecar', expected: 'true', isHidden: false },
      { input: 'hello', expected: 'false', isHidden: false },
      { input: 'Madam', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: 'racecar', output: 'true', explanation: 'Reads identical forwards and backwards.' },
    ],
    constraints: '1 <= length <= 10^5',
    xpReward: 110,
    coinReward: 25,
  },
  {
    title: 'Count Words in Sentence',
    description: 'Read a string line containing words separated by one or more spaces. Print the total count of words.',
    language: 'java',
    topic: 'Strings & StringBuilder',
    learningStage: 3,
    stageName: 'Strings & StringBuilder',
    order: 10,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'Java is an object-oriented language', expected: '5', isHidden: false },
      { input: '  Hello    world  ', expected: '2', isHidden: false },
      { input: 'QuestBoard', expected: '1', isHidden: true },
    ],
    examples: [
      { input: 'Java is an object-oriented language', output: '5', explanation: '5 words.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Toggle Case in String',
    description: 'Read a string from standard input. Convert uppercase letters to lowercase and lowercase letters to uppercase. Keep digits and symbols unchanged. Print the modified string.',
    language: 'java',
    topic: 'Strings & StringBuilder',
    learningStage: 3,
    stageName: 'Strings & StringBuilder',
    order: 11,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'Java Programming 101', expected: 'jAVA pROGRAMMING 101', isHidden: false },
      { input: 'QuestBoard', expected: 'qUESTbOARD', isHidden: false },
    ],
    examples: [
      { input: 'QuestBoard', output: 'qUESTbOARD', explanation: 'Toggled each character casing.' },
    ],
    constraints: '1 <= length <= 10^4',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Character Frequency in Java',
    description: 'Read a lowercase string from standard input. Print the character that appears most frequently followed by its count: `"char: count"`. If tie, choose alphabetically smallest.',
    language: 'java',
    topic: 'Strings & StringBuilder',
    learningStage: 3,
    stageName: 'Strings & StringBuilder',
    order: 12,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'success', expected: 's: 3', isHidden: false },
      { input: 'banana', expected: 'a: 3', isHidden: false },
      { input: 'apple', expected: 'p: 2', isHidden: true },
    ],
    examples: [
      { input: 'success', output: 's: 3', explanation: 's appears 3 times.' },
    ],
    constraints: '1 <= length <= 10^5',
    xpReward: 120,
    coinReward: 30,
  },

  // Stage 4: Arrays & Matrix Basics
  {
    title: 'Second Largest in Array',
    description: 'Read a line of comma-separated or space-separated integers. Find and print the second largest distinct integer. If none exists, print `-1`.',
    language: 'java',
    topic: 'Arrays & Matrix',
    learningStage: 4,
    stageName: 'Arrays & Matrices',
    order: 13,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '12, 35, 1, 10, 34, 1', expected: '34', isHidden: false },
      { input: '10, 10, 10', expected: '-1', isHidden: false },
      { input: '5, 20, 15, 8', expected: '15', isHidden: true },
    ],
    examples: [
      { input: '12, 35, 1, 10, 34, 1', output: '34', explanation: '35 is largest, 34 is second largest.' },
    ],
    constraints: '1 <= array size <= 10^5',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Reverse Array in Place',
    description: 'Read a JSON integer array from standard input. Reverse the elements in place and print the resulting array as a JSON array.',
    language: 'java',
    topic: 'Arrays & Matrix',
    learningStage: 4,
    stageName: 'Arrays & Matrices',
    order: 14,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[1, 2, 3, 4, 5]', expected: '[5,4,3,2,1]', isHidden: false },
      { input: '[10, 20]', expected: '[20,10]', isHidden: false },
      { input: '[42]', expected: '[42]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5]', output: '[5,4,3,2,1]', explanation: 'Elements reversed.' },
    ],
    constraints: '1 <= len <= 10^5',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Is Array Sorted Check',
    description: 'Read a JSON integer array. Determine if the array is sorted in non-decreasing order. Print `"true"` or `"false"`.',
    language: 'java',
    topic: 'Arrays & Matrix',
    learningStage: 4,
    stageName: 'Arrays & Matrices',
    order: 15,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[10, 20, 30, 40, 50]', expected: 'true', isHidden: false },
      { input: '[10, 20, 15, 40]', expected: 'false', isHidden: false },
      { input: '[5]', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: '[10, 20, 30, 40, 50]', output: 'true', explanation: 'Array is non-decreasing.' },
    ],
    constraints: '1 <= len <= 10^5',
    xpReward: 120,
    coinReward: 30,
  },
  {
    title: 'Matrix Diagonal Sum',
    description: 'Given an `n x n` square matrix formatted as a JSON 2D array, calculate the sum of the primary diagonal and secondary diagonal elements. If `n` is odd, subtract the intersecting center element once. Print the total sum.',
    language: 'java',
    topic: 'Arrays & Matrix',
    learningStage: 4,
    stageName: 'Arrays & Matrices',
    order: 16,
    difficulty: 'medium',
    category: 'matrix',
    testCases: [
      { input: '[[1,2,3],[4,5,6],[7,8,9]]', expected: '25', isHidden: false },
      { input: '[[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]]', expected: '8', isHidden: false },
      { input: '[[5]]', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '[[1,2,3],[4,5,6],[7,8,9]]', output: '25', explanation: 'Primary: 1+5+9 = 15; Secondary: 3+5+7 = 15. Center 5 counted once: 15 + 15 - 5 = 25.' },
    ],
    constraints: '1 <= n <= 100',
    xpReward: 135,
    coinReward: 35,
  },

  // Stage 5: OOP & Class Design
  {
    title: 'Rectangle Area & Perimeter Class',
    description: 'Design a `Rectangle` class with width and height. Read two integers `w` and `h` from standard input. Instantiate the object and print `"Area: A, Perimeter: P"`.',
    language: 'java',
    topic: 'Object Oriented Programming',
    learningStage: 5,
    stageName: 'OOP & Class Design',
    order: 17,
    difficulty: 'easy',
    category: 'oop',
    testCases: [
      { input: '5 10', expected: 'Area: 50, Perimeter: 30', isHidden: false },
      { input: '7 7', expected: 'Area: 49, Perimeter: 28', isHidden: false },
      { input: '12 4', expected: 'Area: 48, Perimeter: 32', isHidden: true },
    ],
    examples: [
      { input: '5 10', output: 'Area: 50, Perimeter: 30', explanation: 'Area = 5*10=50, Perimeter = 2*(5+10)=30.' },
    ],
    constraints: '1 <= w, h <= 10^5',
    xpReward: 130,
    coinReward: 30,
  },
  {
    title: 'Bank Account Simulator',
    description: 'Read an initial balance followed by a list of operations (e.g. `deposit 50`, `withdraw 20`). Ensure withdrawal cannot exceed balance (reject with `"Insufficient Funds"`). Print final balance formatted as `"Balance: X"`.',
    language: 'java',
    topic: 'Object Oriented Programming',
    learningStage: 5,
    stageName: 'OOP & Class Design',
    order: 18,
    difficulty: 'medium',
    category: 'oop',
    testCases: [
      { input: '100\ndeposit 50\nwithdraw 30\nwithdraw 200', expected: 'Insufficient Funds\nBalance: 120', isHidden: false },
      { input: '500\nwithdraw 100\ndeposit 200', expected: 'Balance: 600', isHidden: false },
    ],
    examples: [
      { input: '100\ndeposit 50\nwithdraw 30', output: 'Balance: 120', explanation: '100 + 50 - 30 = 120.' },
    ],
    constraints: '1 <= operations <= 100',
    xpReward: 140,
    coinReward: 35,
  },
  {
    title: 'Student Grade Tracker',
    description: 'Read student name and a series of test scores `[85, 90, 95]`. Calculate average score rounded to 2 decimal places and print `"Student: Name, Average: Avg"`.',
    language: 'java',
    topic: 'Object Oriented Programming',
    learningStage: 5,
    stageName: 'OOP & Class Design',
    order: 19,
    difficulty: 'easy',
    category: 'oop',
    testCases: [
      { input: 'Alice\n85 90 95', expected: 'Student: Alice, Average: 90.00', isHidden: false },
      { input: 'Bob\n70 75 80', expected: 'Student: Bob, Average: 75.00', isHidden: false },
    ],
    examples: [
      { input: 'Alice\n85 90 95', output: 'Student: Alice, Average: 90.00', explanation: '(85+90+95)/3 = 90.00' },
    ],
    constraints: '1 <= scores <= 100',
    xpReward: 135,
    coinReward: 30,
  },
  {
    title: 'Polymorphic Shape Area Calculator',
    description: 'Read a shape type (`Circle radius` or `Rectangle w h`) from input. Compute the area (for circle use `Math.PI * r * r` formatted to 2 decimal places, for rectangle `w * h`). Print `"Shape: Type, Area: A"`.',
    language: 'java',
    topic: 'Object Oriented Programming',
    learningStage: 5,
    stageName: 'OOP & Class Design',
    order: 20,
    difficulty: 'medium',
    category: 'oop',
    testCases: [
      { input: 'Circle 5', expected: 'Shape: Circle, Area: 78.54', isHidden: false },
      { input: 'Rectangle 4 6', expected: 'Shape: Rectangle, Area: 24.00', isHidden: false },
    ],
    examples: [
      { input: 'Circle 5', output: 'Shape: Circle, Area: 78.54', explanation: 'PI * 25 = 78.54' },
    ],
    constraints: 'Dimensions >= 1',
    xpReward: 145,
    coinReward: 35,
  },

  // Stage 6: Java Collections Framework
  {
    title: 'ArrayList Sort & Filter',
    description: 'Read a JSON array of integers from standard input. Using `ArrayList` and `Collections.sort`, filter out negative numbers and sort the remaining in ascending order. Print as a JSON array.',
    language: 'java',
    topic: 'Collections Framework',
    learningStage: 6,
    stageName: 'Java Collections Framework',
    order: 21,
    difficulty: 'easy',
    category: 'collections',
    testCases: [
      { input: '[5, -3, 12, -8, 0, 7]', expected: '[0,5,7,12]', isHidden: false },
      { input: '[-1, -2, -3]', expected: '[]', isHidden: false },
      { input: '[9, 4, 1, 8]', expected: '[1,4,8,9]', isHidden: true },
    ],
    examples: [
      { input: '[5, -3, 12, -8, 0, 7]', output: '[0,5,7,12]', explanation: 'Negatives filtered out, sorted ascending.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 140,
    coinReward: 35,
  },
  {
    title: 'Two Sum with HashMap',
    description: 'Given a JSON array of integers on line 1 and integer `target` on line 2, find the two indices using a `HashMap<Integer, Integer>`. Print indices as a JSON array `[i, j]`.',
    language: 'java',
    topic: 'Collections Framework',
    learningStage: 6,
    stageName: 'Java Collections Framework',
    order: 22,
    difficulty: 'medium',
    category: 'collections',
    testCases: [
      { input: '[2, 7, 11, 15]\n9', expected: '[0,1]', isHidden: false },
      { input: '[3, 2, 4]\n6', expected: '[1,2]', isHidden: false },
      { input: '[3, 3]\n6', expected: '[0,1]', isHidden: true },
    ],
    examples: [
      { input: '[2, 7, 11, 15]\n9', output: '[0,1]', explanation: '2 + 7 = 9 at indices 0 and 1.' },
    ],
    constraints: '2 <= size <= 10^5',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Unique Elements with HashSet',
    description: 'Read a JSON array of numbers. Using a `HashSet`, deduplicate the numbers, sort them in ascending order, and print as a JSON array.',
    language: 'java',
    topic: 'Collections Framework',
    learningStage: 6,
    stageName: 'Java Collections Framework',
    order: 23,
    difficulty: 'easy',
    category: 'collections',
    testCases: [
      { input: '[1, 2, 2, 3, 4, 4, 5]', expected: '[1,2,3,4,5]', isHidden: false },
      { input: '[9, 9, 9]', expected: '[9]', isHidden: false },
      { input: '[10, 5, 10, 5]', expected: '[5,10]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 2, 3, 4, 4, 5]', output: '[1,2,3,4,5]', explanation: 'Unique sorted numbers.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 135,
    coinReward: 35,
  },
  {
    title: 'Frequency Map with TreeMap',
    description: 'Read a space-separated sentence of words. Using `TreeMap<String, Integer>`, count word frequencies and print sorted keys formatted as `"word:count, word:count"`.',
    language: 'java',
    topic: 'Collections Framework',
    learningStage: 6,
    stageName: 'Java Collections Framework',
    order: 24,
    difficulty: 'medium',
    category: 'collections',
    testCases: [
      { input: 'cat dog bird dog cat cat', expected: 'bird:1, cat:3, dog:2', isHidden: false },
      { input: 'java java oop', expected: 'java:2, oop:1', isHidden: false },
    ],
    examples: [
      { input: 'cat dog bird dog cat cat', output: 'bird:1, cat:3, dog:2', explanation: 'Alphabetically sorted frequencies.' },
    ],
    constraints: 'Words <= 10^4',
    xpReward: 145,
    coinReward: 40,
  },

  // Stage 7: Exception Handling & Generics
  {
    title: 'Safe Integer Parser',
    description: 'Read a string from standard input. Attempt to parse it as an integer using `Integer.parseInt()`. If parsing throws `NumberFormatException`, print `"Invalid Integer: fallback 0"`. Otherwise print `"Parsed: X"`.',
    language: 'java',
    topic: 'Exceptions & Generics',
    learningStage: 7,
    stageName: 'Exceptions & Generics',
    order: 25,
    difficulty: 'easy',
    category: 'exceptions',
    testCases: [
      { input: '1234', expected: 'Parsed: 1234', isHidden: false },
      { input: 'abc', expected: 'Invalid Integer: fallback 0', isHidden: false },
      { input: '-999', expected: 'Parsed: -999', isHidden: true },
    ],
    examples: [
      { input: 'abc', output: 'Invalid Integer: fallback 0', explanation: 'Catches exception cleanly.' },
    ],
    constraints: 'String length <= 100',
    xpReward: 140,
    coinReward: 35,
  },
  {
    title: 'Generic Pair Container',
    description: 'Implement a generic `Pair<K, V>` class in Java. Read key type and value from standard input (e.g. `"id 101"`), instantiate `Pair`, and print `"Pair[key=id, value=101]"`.',
    language: 'java',
    topic: 'Exceptions & Generics',
    learningStage: 7,
    stageName: 'Exceptions & Generics',
    order: 26,
    difficulty: 'medium',
    category: 'generics',
    testCases: [
      { input: 'id 101', expected: 'Pair[key=id, value=101]', isHidden: false },
      { input: 'username questmaster', expected: 'Pair[key=username, value=questmaster]', isHidden: false },
    ],
    examples: [
      { input: 'id 101', output: 'Pair[key=id, value=101]', explanation: 'Generic Pair container.' },
    ],
    constraints: 'Key and Value are alphanumeric strings.',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Valid Parentheses with Stack',
    description: 'Read a string of brackets `()[]{}` from standard input. Use `java.util.Stack<Character>` to verify if brackets are properly closed and nested. Print `"true"` or `"false"`.',
    language: 'java',
    topic: 'Exceptions & Generics',
    learningStage: 7,
    stageName: 'Exceptions & Generics',
    order: 27,
    difficulty: 'medium',
    category: 'stacks',
    testCases: [
      { input: '()[]{}', expected: 'true', isHidden: false },
      { input: '(]', expected: 'false', isHidden: false },
      { input: '{[]}', expected: 'true', isHidden: true },
      { input: '([)]', expected: 'false', isHidden: true },
    ],
    examples: [
      { input: '()[]{}', output: 'true', explanation: 'Valid stack bracket matching.' },
    ],
    constraints: '1 <= len <= 10^4',
    xpReward: 155,
    coinReward: 40,
  },
  {
    title: 'First Non-Repeating Character',
    description: 'Read a string from standard input. Find the first character that does not repeat anywhere in the string. If all repeat, print `"None"`.',
    language: 'java',
    topic: 'Exceptions & Generics',
    learningStage: 7,
    stageName: 'Exceptions & Generics',
    order: 28,
    difficulty: 'medium',
    category: 'collections',
    testCases: [
      { input: 'leetcode', expected: 'l', isHidden: false },
      { input: 'loveleetcode', expected: 'v', isHidden: false },
      { input: 'aabb', expected: 'None', isHidden: true },
    ],
    examples: [
      { input: 'leetcode', output: 'l', explanation: 'l is the first unique character.' },
    ],
    constraints: '1 <= length <= 10^5',
    xpReward: 155,
    coinReward: 40,
  },

  // Stage 8: DSA & Algorithms in Java
  {
    title: 'Binary Search Algorithm in Java',
    description: 'Read a sorted JSON integer array on line 1 and integer `target` on line 2. Find and print the index of `target`, or `-1` if not found.',
    language: 'java',
    topic: 'DSA & Algorithms',
    learningStage: 8,
    stageName: 'DSA & Algorithms',
    order: 29,
    difficulty: 'easy',
    category: 'searching',
    testCases: [
      { input: '[-1, 0, 3, 5, 9, 12]\n9', expected: '4', isHidden: false },
      { input: '[-1, 0, 3, 5, 9, 12]\n2', expected: '-1', isHidden: false },
      { input: '[1, 2, 3, 4, 5, 6, 7]\n6', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '[-1, 0, 3, 5, 9, 12]\n9', output: '4', explanation: '9 is at index 4.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Merge Two Sorted Arrays',
    description: 'Read two sorted JSON arrays from line 1 and line 2. Merge them into a single sorted JSON array in O(n+m) time.',
    language: 'java',
    topic: 'DSA & Algorithms',
    learningStage: 8,
    stageName: 'DSA & Algorithms',
    order: 30,
    difficulty: 'medium',
    category: 'sorting',
    testCases: [
      { input: '[1, 2, 4]\n[1, 3, 4]', expected: '[1,1,2,3,4,4]', isHidden: false },
      { input: '[]\n[0]', expected: '[0]', isHidden: false },
      { input: '[2, 5, 8]\n[1, 3, 7, 9]', expected: '[1,2,3,5,7,8,9]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 4]\n[1, 3, 4]', output: '[1,1,2,3,4,4]', explanation: 'Merged sorted arrays.' },
    ],
    constraints: '1 <= n+m <= 10^5',
    xpReward: 165,
    coinReward: 45,
  },
  {
    title: 'Maximum Subarray (Kadane in Java)',
    description: 'Given a JSON array of integers, find the contiguous subarray with the largest sum and print its sum.',
    language: 'java',
    topic: 'DSA & Algorithms',
    learningStage: 8,
    stageName: 'DSA & Algorithms',
    order: 31,
    difficulty: 'medium',
    category: 'dynamic-programming',
    testCases: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', expected: '6', isHidden: false },
      { input: '[1]', expected: '1', isHidden: false },
      { input: '[5, 4, -1, 7, 8]', expected: '23', isHidden: true },
    ],
    examples: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', output: '6', explanation: 'Max sum subarray is [4, -1, 2, 1] with sum 6.' },
    ],
    constraints: '1 <= size <= 10^5',
    xpReward: 175,
    coinReward: 50,
  },
  {
    title: 'Longest Consecutive Sequence',
    description: 'Given an unsorted JSON array of integers, find the length of the longest consecutive elements sequence in O(n) time using a HashSet. Print the length.',
    language: 'java',
    topic: 'DSA & Algorithms',
    learningStage: 8,
    stageName: 'DSA & Algorithms',
    order: 32,
    difficulty: 'hard',
    category: 'hash-set',
    testCases: [
      { input: '[100, 4, 200, 1, 3, 2]', expected: '4', isHidden: false },
      { input: '[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]', expected: '9', isHidden: false },
      { input: '[]', expected: '0', isHidden: true },
    ],
    examples: [
      { input: '[100, 4, 200, 1, 3, 2]', output: '4', explanation: 'The longest consecutive elements sequence is [1, 2, 3, 4]. Length is 4.' },
    ],
    constraints: '0 <= length <= 10^5',
    xpReward: 200,
    coinReward: 60,
  },
];
