export const pythonChallenges = [
  // Stage 1: Python Fundamentals
  {
    title: 'Hello Python',
    description: 'Write a Python program that prints the exact message `"Hello, Python!"` to standard output.',
    language: 'python',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Python Fundamentals',
    order: 1,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '', expected: 'Hello, Python!', isHidden: false },
      { input: 'test', expected: 'Hello, Python!', isHidden: true },
    ],
    examples: [
      { input: '(none)', output: 'Hello, Python!', explanation: 'The program outputs the greeting string.' },
    ],
    constraints: 'Standard output must match exact casing and punctuation.',
    xpReward: 75,
    coinReward: 20,
  },
  {
    title: 'Sum of Two Numbers',
    description: 'Read two integers from standard input (separated by whitespace or on separate lines) and print their sum.',
    language: 'python',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Python Fundamentals',
    order: 2,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '3 5', expected: '8', isHidden: false },
      { input: '10\n25', expected: '35', isHidden: false },
      { input: '-7 14', expected: '7', isHidden: true },
      { input: '1000 2500', expected: '3500', isHidden: true },
    ],
    examples: [
      { input: '3 5', output: '8', explanation: '3 + 5 = 8' },
    ],
    constraints: '-10^6 <= a, b <= 10^6',
    xpReward: 80,
    coinReward: 20,
  },
  {
    title: 'Celsius to Fahrenheit',
    description: 'Read a floating-point temperature in Celsius from standard input. Convert it to Fahrenheit using the formula `(C * 9/5) + 32` and print the result formatted to 1 decimal place (e.g. `98.6`).',
    language: 'python',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Python Fundamentals',
    order: 3,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '0', expected: '32.0', isHidden: false },
      { input: '37', expected: '98.6', isHidden: false },
      { input: '100', expected: '212.0', isHidden: true },
      { input: '-40', expected: '-40.0', isHidden: true },
    ],
    examples: [
      { input: '37', output: '98.6', explanation: '(37 * 9/5) + 32 = 98.6' },
    ],
    constraints: '-100.0 <= Celsius <= 1000.0',
    xpReward: 85,
    coinReward: 20,
  },
  {
    title: 'Odd or Even Checker',
    description: 'Read an integer from standard input. Print `"Even"` if the number is even, and `"Odd"` if the number is odd.',
    language: 'python',
    topic: 'Fundamentals',
    learningStage: 1,
    stageName: 'Python Fundamentals',
    order: 4,
    difficulty: 'easy',
    category: 'fundamentals',
    testCases: [
      { input: '4', expected: 'Even', isHidden: false },
      { input: '7', expected: 'Odd', isHidden: false },
      { input: '0', expected: 'Even', isHidden: true },
      { input: '-11', expected: 'Odd', isHidden: true },
    ],
    examples: [
      { input: '4', output: 'Even', explanation: '4 is divisible by 2.' },
    ],
    constraints: '-10^9 <= n <= 10^9',
    xpReward: 85,
    coinReward: 20,
  },

  // Stage 2: Control Flow & Loops
  {
    title: 'FizzBuzz Sequence',
    description: 'Given an integer `n` from standard input, print numbers from 1 to `n` separated by spaces. For multiples of 3, print `"Fizz"`; for multiples of 5, print `"Buzz"`; and for numbers which are multiples of both 3 and 5, print `"FizzBuzz"`.',
    language: 'python',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 5,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '5', expected: '1 2 Fizz 4 Buzz', isHidden: false },
      { input: '15', expected: '1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz', isHidden: false },
      { input: '1', expected: '1', isHidden: true },
      { input: '8', expected: '1 2 Fizz 4 Buzz Fizz 7 8', isHidden: true },
    ],
    examples: [
      { input: '5', output: '1 2 Fizz 4 Buzz', explanation: '3 is replaced by Fizz, 5 by Buzz.' },
    ],
    constraints: '1 <= n <= 100',
    xpReward: 100,
    coinReward: 25,
  },
  {
    title: 'Factorial Calculator',
    description: 'Read a non-negative integer `n` from standard input. Calculate `n!` (the product of all positive integers less than or equal to `n`) and print the result. Note that `0! = 1`.',
    language: 'python',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 6,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '5', expected: '120', isHidden: false },
      { input: '0', expected: '1', isHidden: false },
      { input: '7', expected: '5040', isHidden: true },
      { input: '10', expected: '3628800', isHidden: true },
    ],
    examples: [
      { input: '5', output: '120', explanation: '5 * 4 * 3 * 2 * 1 = 120' },
    ],
    constraints: '0 <= n <= 20',
    xpReward: 100,
    coinReward: 25,
  },
  {
    title: 'Sum of Digits',
    description: 'Given a non-negative integer from standard input, compute the sum of its individual digits and print the result.',
    language: 'python',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 7,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '1234', expected: '10', isHidden: false },
      { input: '987', expected: '24', isHidden: false },
      { input: '5', expected: '5', isHidden: true },
      { input: '10002', expected: '3', isHidden: true },
    ],
    examples: [
      { input: '1234', output: '10', explanation: '1 + 2 + 3 + 4 = 10' },
    ],
    constraints: '0 <= n <= 10^12',
    xpReward: 105,
    coinReward: 25,
  },
  {
    title: 'Multiplication Table Row',
    description: 'Read an integer `n` from standard input. Print the first 10 multiples of `n` (`n * 1` through `n * 10`) on a single line separated by spaces.',
    language: 'python',
    topic: 'Control Flow',
    learningStage: 2,
    stageName: 'Control Flow & Loops',
    order: 8,
    difficulty: 'easy',
    category: 'control-flow',
    testCases: [
      { input: '3', expected: '3 6 9 12 15 18 21 24 27 30', isHidden: false },
      { input: '7', expected: '7 14 21 28 35 42 49 56 63 70', isHidden: false },
      { input: '12', expected: '12 24 36 48 60 72 84 96 108 120', isHidden: true },
    ],
    examples: [
      { input: '3', output: '3 6 9 12 15 18 21 24 27 30', explanation: 'First 10 multiples of 3.' },
    ],
    constraints: '1 <= n <= 1000',
    xpReward: 105,
    coinReward: 25,
  },

  // Stage 3: Strings & Slicing
  {
    title: 'Reverse a String',
    description: 'Read a string from standard input and print the reversed string.',
    language: 'python',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Slicing',
    order: 9,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'questboard', expected: 'draobtseuq', isHidden: false },
      { input: 'Python3', expected: '3nohtyP', isHidden: false },
      { input: 'racecar', expected: 'racecar', isHidden: true },
      { input: 'Hello World!', expected: '!dlroW olleH', isHidden: true },
    ],
    examples: [
      { input: 'questboard', output: 'draobtseuq', explanation: 'String reversed character by character.' },
    ],
    constraints: 'Length of string <= 10^4',
    xpReward: 110,
    coinReward: 25,
  },
  {
    title: 'Palindrome String Checker',
    description: 'Read a single string line. Determine if it is a palindrome (reads identical forwards and backwards), ignoring case and non-alphanumeric characters. Print `"true"` or `"false"`.',
    language: 'python',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Slicing',
    order: 10,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'A man, a plan, a canal: Panama', expected: 'true', isHidden: false },
      { input: 'race a car', expected: 'false', isHidden: false },
      { input: 'No lemon, no melon', expected: 'true', isHidden: true },
      { input: 'Was it a car or a cat I saw?', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: 'A man, a plan, a canal: Panama', output: 'true', explanation: 'amanaplanacanalpanama is a palindrome.' },
    ],
    constraints: 'String length <= 10^5',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Vowel and Consonant Counter',
    description: 'Read a string from standard input. Count the number of vowels (a, e, i, o, u, case-insensitive) and the number of consonants (English alphabetic letters that are not vowels). Print `"Vowels: X, Consonants: Y"`.',
    language: 'python',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Slicing',
    order: 11,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'Hello World', expected: 'Vowels: 3, Consonants: 7', isHidden: false },
      { input: 'Python Programming', expected: 'Vowels: 4, Consonants: 13', isHidden: false },
      { input: 'AEIOU', expected: 'Vowels: 5, Consonants: 0', isHidden: true },
    ],
    examples: [
      { input: 'Hello World', output: 'Vowels: 3, Consonants: 7', explanation: 'e, o, o are vowels; h, l, l, w, r, l, d are consonants.' },
    ],
    constraints: 'String length <= 10^4',
    xpReward: 115,
    coinReward: 30,
  },
  {
    title: 'Title Case Converter',
    description: 'Read a space-separated sentence from standard input. Convert each word so that its first letter is capitalized and all remaining letters are lowercase. Print the resulting sentence.',
    language: 'python',
    topic: 'Strings',
    learningStage: 3,
    stageName: 'Strings & Slicing',
    order: 12,
    difficulty: 'easy',
    category: 'strings',
    testCases: [
      { input: 'the QUICK brown FOX', expected: 'The Quick Brown Fox', isHidden: false },
      { input: 'learn python step by step', expected: 'Learn Python Step By Step', isHidden: false },
      { input: 'questboard mastery', expected: 'Questboard Mastery', isHidden: true },
    ],
    examples: [
      { input: 'the QUICK brown FOX', output: 'The Quick Brown Fox', explanation: 'Each word has initial cap and lowercase rest.' },
    ],
    constraints: '1 <= words <= 1000',
    xpReward: 120,
    coinReward: 30,
  },

  // Stage 4: Lists & Tuples
  {
    title: 'Find Min and Max in List',
    description: 'Given a JSON array of integers from standard input, print the minimum and maximum elements formatted as `"Min: X, Max: Y"`.',
    language: 'python',
    topic: 'Collections',
    learningStage: 4,
    stageName: 'Lists & Tuples',
    order: 13,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[3, 7, 2, 9, 1, 5]', expected: 'Min: 1, Max: 9', isHidden: false },
      { input: '[-10, 0, 50, -25, 12]', expected: 'Min: -25, Max: 50', isHidden: false },
      { input: '[42]', expected: 'Min: 42, Max: 42', isHidden: true },
    ],
    examples: [
      { input: '[3, 7, 2, 9, 1, 5]', output: 'Min: 1, Max: 9', explanation: '1 is minimum, 9 is maximum.' },
    ],
    constraints: '1 <= len(nums) <= 10^5',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Remove Duplicates Preserving Order',
    description: 'Given a JSON array of integers from standard input, remove all duplicate numbers while preserving the original order of their first appearance. Print the result as a JSON array.',
    language: 'python',
    topic: 'Collections',
    learningStage: 4,
    stageName: 'Lists & Tuples',
    order: 14,
    difficulty: 'easy',
    category: 'arrays',
    testCases: [
      { input: '[1, 2, 3, 2, 1, 4, 5, 4]', expected: '[1,2,3,4,5]', isHidden: false },
      { input: '[5, 5, 5, 5]', expected: '[5]', isHidden: false },
      { input: '[10, 20, 30]', expected: '[10,20,30]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 2, 1, 4, 5, 4]', output: '[1,2,3,4,5]', explanation: 'Only the first occurrences of 2, 1, 4 are kept.' },
    ],
    constraints: '1 <= len(nums) <= 10^4',
    xpReward: 125,
    coinReward: 30,
  },
  {
    title: 'Chunk a List into Sublists',
    description: 'Read standard input containing a JSON array on line 1 and an integer `k` (chunk size) on line 2. Split the array into sublists of length `k` (the last sublist may have fewer elements). Output the result as a JSON array of lists.',
    language: 'python',
    topic: 'Collections',
    learningStage: 4,
    stageName: 'Lists & Tuples',
    order: 15,
    difficulty: 'medium',
    category: 'arrays',
    testCases: [
      { input: '[1, 2, 3, 4, 5, 6, 7]\n3', expected: '[[1,2,3],[4,5,6],[7]]', isHidden: false },
      { input: '[10, 20, 30, 40]\n2', expected: '[[10,20],[30,40]]', isHidden: false },
      { input: '[1, 2]\n5', expected: '[[1,2]]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5, 6, 7]\n3', output: '[[1,2,3],[4,5,6],[7]]', explanation: 'Chunks of size 3 with remainder [7].' },
    ],
    constraints: '1 <= len(nums) <= 10^4, k >= 1',
    xpReward: 130,
    coinReward: 35,
  },
  {
    title: 'Rotate List Right by K Steps',
    description: 'Read a JSON array on line 1 and an integer `k` on line 2. Rotate the list to the right by `k` steps and print the rotated list as a JSON array.',
    language: 'python',
    topic: 'Collections',
    learningStage: 4,
    stageName: 'Lists & Tuples',
    order: 16,
    difficulty: 'medium',
    category: 'arrays',
    testCases: [
      { input: '[1, 2, 3, 4, 5, 6, 7]\n3', expected: '[5,6,7,1,2,3,4]', isHidden: false },
      { input: '[-1, -100, 3, 99]\n2', expected: '[3,99,-1,-100]', isHidden: false },
      { input: '[1, 2]\n3', expected: '[2,1]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 3, 4, 5, 6, 7]\n3', output: '[5,6,7,1,2,3,4]', explanation: 'Shift elements right by 3 positions.' },
    ],
    constraints: '1 <= len(nums) <= 10^5, 0 <= k <= 10^9',
    xpReward: 135,
    coinReward: 35,
  },

  // Stage 5: Dictionaries & Sets
  {
    title: 'Word Frequency Counter',
    description: 'Given a space-separated string from standard input, count the frequency of each lowercase word. Print the word with the highest frequency followed by its count: `"word: count"`. If there is a tie, print the lexicographically smallest word.',
    language: 'python',
    topic: 'Dictionaries & Sets',
    learningStage: 5,
    stageName: 'Dictionaries & Sets',
    order: 17,
    difficulty: 'medium',
    category: 'dictionaries',
    testCases: [
      { input: 'apple banana apple orange banana apple', expected: 'apple: 3', isHidden: false },
      { input: 'cat dog bird dog cat', expected: 'cat: 2', isHidden: false },
      { input: 'hello world python', expected: 'hello: 1', isHidden: true },
    ],
    examples: [
      { input: 'apple banana apple orange banana apple', output: 'apple: 3', explanation: 'apple appears 3 times.' },
    ],
    constraints: 'Total words <= 10^4',
    xpReward: 135,
    coinReward: 35,
  },
  {
    title: 'Two Sum with Hash Map',
    description: 'Given a JSON array of integers on line 1 and an integer `target` on line 2, find the 0-based indices of the two numbers that add up to `target`. Print the indices as a JSON array `[i, j]`. Assume exactly one valid solution exists.',
    language: 'python',
    topic: 'Dictionaries & Sets',
    learningStage: 5,
    stageName: 'Dictionaries & Sets',
    order: 18,
    difficulty: 'medium',
    category: 'arrays',
    testCases: [
      { input: '[2, 7, 11, 15]\n9', expected: '[0,1]', isHidden: false },
      { input: '[3, 2, 4]\n6', expected: '[1,2]', isHidden: false },
      { input: '[3, 3]\n6', expected: '[0,1]', isHidden: true },
      { input: '[1, 5, 8, 12, 19]\n20', expected: '[0,4]', isHidden: true },
    ],
    examples: [
      { input: '[2, 7, 11, 15]\n9', output: '[0,1]', explanation: 'nums[0] + nums[1] = 2 + 7 = 9' },
    ],
    constraints: '2 <= len(nums) <= 10^5',
    xpReward: 140,
    coinReward: 35,
  },
  {
    title: 'Set Intersection',
    description: 'Read two JSON integer arrays from standard input (line 1 and line 2). Compute their set intersection (unique numbers present in both arrays), sort them in ascending order, and print as a JSON array.',
    language: 'python',
    topic: 'Dictionaries & Sets',
    learningStage: 5,
    stageName: 'Dictionaries & Sets',
    order: 19,
    difficulty: 'easy',
    category: 'sets',
    testCases: [
      { input: '[1, 2, 2, 1]\n[2, 2]', expected: '[2]', isHidden: false },
      { input: '[4, 9, 5]\n[9, 4, 9, 8, 4]', expected: '[4,9]', isHidden: false },
      { input: '[1, 3, 5]\n[2, 4, 6]', expected: '[]', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 2, 1]\n[2, 2]', output: '[2]', explanation: '2 is the only common unique value.' },
    ],
    constraints: '1 <= len(nums) <= 10^4',
    xpReward: 130,
    coinReward: 30,
  },
  {
    title: 'Group Anagrams',
    description: 'Read a JSON array of strings from standard input. Group the anagrams together and print the grouped list of lists as JSON. Inner lists should have their items preserved in first appearance order, and groups should be ordered by their first appearance.',
    language: 'python',
    topic: 'Dictionaries & Sets',
    learningStage: 5,
    stageName: 'Dictionaries & Sets',
    order: 20,
    difficulty: 'medium',
    category: 'strings',
    testCases: [
      { input: '["eat","tea","tan","ate","nat","bat"]', expected: '[["eat","tea","ate"],["tan","nat"],["bat"]]', isHidden: false },
      { input: '["a"]', expected: '[["a"]]', isHidden: false },
      { input: '["rat","tar","art","star"]', expected: '[["rat","tar","art"],["star"]]', isHidden: true },
    ],
    examples: [
      { input: '["eat","tea","tan","ate","nat","bat"]', output: '[["eat","tea","ate"],["tan","nat"],["bat"]]', explanation: 'Anagrams share identical character counts.' },
    ],
    constraints: '1 <= words <= 10^4',
    xpReward: 145,
    coinReward: 40,
  },

  // Stage 6: Functions & Recursion
  {
    title: 'N-th Fibonacci Number',
    description: 'Given an integer `n` from standard input, return the `n`-th Fibonacci number where `F(0) = 0`, `F(1) = 1`, and `F(n) = F(n-1) + F(n-2)`.',
    language: 'python',
    topic: 'Functions & Recursion',
    learningStage: 6,
    stageName: 'Functions & Recursion',
    order: 21,
    difficulty: 'easy',
    category: 'recursion',
    testCases: [
      { input: '6', expected: '8', isHidden: false },
      { input: '10', expected: '55', isHidden: false },
      { input: '0', expected: '0', isHidden: true },
      { input: '20', expected: '6765', isHidden: true },
    ],
    examples: [
      { input: '6', output: '8', explanation: 'Sequence: 0, 1, 1, 2, 3, 5, 8' },
    ],
    constraints: '0 <= n <= 40',
    xpReward: 135,
    coinReward: 30,
  },
  {
    title: 'Power of a Number (Pow)',
    description: 'Read base `x` (float) on line 1 and integer exponent `n` on line 2. Calculate `x^n` and print the result formatted to 2 decimal places.',
    language: 'python',
    topic: 'Functions & Recursion',
    learningStage: 6,
    stageName: 'Functions & Recursion',
    order: 22,
    difficulty: 'medium',
    category: 'math',
    testCases: [
      { input: '2.0\n10', expected: '1024.00', isHidden: false },
      { input: '2.1\n3', expected: '9.26', isHidden: false },
      { input: '2.0\n-2', expected: '0.25', isHidden: true },
    ],
    examples: [
      { input: '2.0\n10', output: '1024.00', explanation: '2.0^10 = 1024' },
    ],
    constraints: '-100.0 < x < 100.0, -100 <= n <= 100',
    xpReward: 140,
    coinReward: 35,
  },
  {
    title: 'Flatten Nested List Recursively',
    description: 'Read an arbitrarily nested JSON array of integers from standard input. Flatten it into a 1D list and print the result as a JSON array.',
    language: 'python',
    topic: 'Functions & Recursion',
    learningStage: 6,
    stageName: 'Functions & Recursion',
    order: 23,
    difficulty: 'medium',
    category: 'recursion',
    testCases: [
      { input: '[1, [2, [3, 4], 5], 6]', expected: '[1,2,3,4,5,6]', isHidden: false },
      { input: '[[[1]], [2], [[3]]]', expected: '[1,2,3]', isHidden: false },
      { input: '[10, 20, [30]]', expected: '[10,20,30]', isHidden: true },
    ],
    examples: [
      { input: '[1, [2, [3, 4], 5], 6]', output: '[1,2,3,4,5,6]', explanation: 'All nested levels flattened.' },
    ],
    constraints: 'Depth <= 20',
    xpReward: 145,
    coinReward: 40,
  },
  {
    title: 'Greatest Common Divisor (GCD)',
    description: 'Read two positive integers `a` and `b` from standard input. Compute their Greatest Common Divisor (GCD) using the Euclidean algorithm and print the result.',
    language: 'python',
    topic: 'Functions & Recursion',
    learningStage: 6,
    stageName: 'Functions & Recursion',
    order: 24,
    difficulty: 'easy',
    category: 'math',
    testCases: [
      { input: '48 18', expected: '6', isHidden: false },
      { input: '101 10', expected: '1', isHidden: false },
      { input: '100 25', expected: '25', isHidden: true },
      { input: '1071 462', expected: '21', isHidden: true },
    ],
    examples: [
      { input: '48 18', output: '6', explanation: 'GCD of 48 and 18 is 6.' },
    ],
    constraints: '1 <= a, b <= 10^9',
    xpReward: 120,
    coinReward: 25,
  },

  // Stage 7: Problem Solving & Two Pointers
  {
    title: 'Valid Parentheses',
    description: 'Given a string containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid. An input string is valid if open brackets are closed by the same type of brackets in the correct order. Print `"true"` or `"false"`.',
    language: 'python',
    topic: 'Problem Solving',
    learningStage: 7,
    stageName: 'Problem Solving & Two Pointers',
    order: 25,
    difficulty: 'medium',
    category: 'stacks',
    testCases: [
      { input: '()[]{}', expected: 'true', isHidden: false },
      { input: '(]', expected: 'false', isHidden: false },
      { input: '([)]', expected: 'false', isHidden: true },
      { input: '{[]}', expected: 'true', isHidden: true },
    ],
    examples: [
      { input: '()[]{}', output: 'true', explanation: 'All brackets closed appropriately.' },
    ],
    constraints: '1 <= len(s) <= 10^4',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Move Zeroes to End',
    description: 'Given a JSON array of numbers, move all `0`s to the end of the array while maintaining the relative order of the non-zero elements. Print the modified array as JSON.',
    language: 'python',
    topic: 'Problem Solving',
    learningStage: 7,
    stageName: 'Problem Solving & Two Pointers',
    order: 26,
    difficulty: 'easy',
    category: 'two-pointers',
    testCases: [
      { input: '[0, 1, 0, 3, 12]', expected: '[1,3,12,0,0]', isHidden: false },
      { input: '[0]', expected: '[0]', isHidden: false },
      { input: '[4, 2, 4, 0, 0, 3, 0, 5, 1, 0]', expected: '[4,2,4,3,5,1,0,0,0,0]', isHidden: true },
    ],
    examples: [
      { input: '[0, 1, 0, 3, 12]', output: '[1,3,12,0,0]', explanation: 'Non-zeroes preserved in order; zeroes shifted.' },
    ],
    constraints: '1 <= len(nums) <= 10^4',
    xpReward: 135,
    coinReward: 35,
  },
  {
    title: 'Container With Most Water',
    description: 'Given a JSON array of non-negative integers representing vertical line heights, find two lines that together with the x-axis form a container that contains the most water. Print the maximum water area.',
    language: 'python',
    topic: 'Problem Solving',
    learningStage: 7,
    stageName: 'Problem Solving & Two Pointers',
    order: 27,
    difficulty: 'medium',
    category: 'two-pointers',
    testCases: [
      { input: '[1, 8, 6, 2, 5, 4, 8, 3, 7]', expected: '49', isHidden: false },
      { input: '[1, 1]', expected: '1', isHidden: false },
      { input: '[4, 3, 2, 1, 4]', expected: '16', isHidden: true },
    ],
    examples: [
      { input: '[1, 8, 6, 2, 5, 4, 8, 3, 7]', output: '49', explanation: 'Max area formed between index 1 and index 8: min(8,7) * 7 = 49.' },
    ],
    constraints: '2 <= len(height) <= 10^5',
    xpReward: 160,
    coinReward: 45,
  },
  {
    title: 'Longest Substring Without Repeating Characters',
    description: 'Given a string from standard input, find the length of the longest substring without duplicate characters.',
    language: 'python',
    topic: 'Problem Solving',
    learningStage: 7,
    stageName: 'Problem Solving & Two Pointers',
    order: 28,
    difficulty: 'medium',
    category: 'sliding-window',
    testCases: [
      { input: 'abcabcbb', expected: '3', isHidden: false },
      { input: 'bbbbb', expected: '1', isHidden: false },
      { input: 'pwwkew', expected: '3', isHidden: true },
      { input: '', expected: '0', isHidden: true },
    ],
    examples: [
      { input: 'abcabcbb', output: '3', explanation: 'The answer is "abc", with length 3.' },
    ],
    constraints: '0 <= len(s) <= 5 * 10^4',
    xpReward: 165,
    coinReward: 45,
  },

  // Stage 8: Data Structures & Algorithms
  {
    title: 'Binary Search Implementation',
    description: 'Read a sorted JSON array of integers on line 1 and a target integer on line 2. Return the 0-based index of target if it exists, otherwise print `-1`. Must run in O(log n) time complexity.',
    language: 'python',
    topic: 'Data Structures & Algorithms',
    learningStage: 8,
    stageName: 'Data Structures & Algorithms',
    order: 29,
    difficulty: 'easy',
    category: 'searching',
    testCases: [
      { input: '[-1, 0, 3, 5, 9, 12]\n9', expected: '4', isHidden: false },
      { input: '[-1, 0, 3, 5, 9, 12]\n2', expected: '-1', isHidden: false },
      { input: '[5]\n5', expected: '0', isHidden: true },
      { input: '[1, 3, 5, 7, 9, 11, 13, 15, 17]\n11', expected: '5', isHidden: true },
    ],
    examples: [
      { input: '[-1, 0, 3, 5, 9, 12]\n9', output: '4', explanation: '9 exists at index 4.' },
    ],
    constraints: '1 <= len(nums) <= 10^5',
    xpReward: 150,
    coinReward: 40,
  },
  {
    title: 'Merge Overlapping Intervals',
    description: 'Read a JSON array of intervals `[[start, end], ...]` from standard input. Merge all overlapping intervals and print the resulting sorted intervals as JSON.',
    language: 'python',
    topic: 'Data Structures & Algorithms',
    learningStage: 8,
    stageName: 'Data Structures & Algorithms',
    order: 30,
    difficulty: 'medium',
    category: 'intervals',
    testCases: [
      { input: '[[1, 3], [2, 6], [8, 10], [15, 18]]', expected: '[[1,6],[8,10],[15,18]]', isHidden: false },
      { input: '[[1, 4], [4, 5]]', expected: '[[1,5]]', isHidden: false },
      { input: '[[1, 4], [2, 3]]', expected: '[[1,4]]', isHidden: true },
    ],
    examples: [
      { input: '[[1, 3], [2, 6], [8, 10], [15, 18]]', output: '[[1,6],[8,10],[15,18]]', explanation: 'Intervals [1,3] and [2,6] overlap into [1,6].' },
    ],
    constraints: '1 <= intervals.length <= 10^4',
    xpReward: 170,
    coinReward: 45,
  },
  {
    title: 'Maximum Subarray Sum (Kadane)',
    description: 'Given a JSON integer array, find the contiguous subarray (containing at least one number) which has the largest sum and print its sum.',
    language: 'python',
    topic: 'Data Structures & Algorithms',
    learningStage: 8,
    stageName: 'Data Structures & Algorithms',
    order: 31,
    difficulty: 'medium',
    category: 'dynamic-programming',
    testCases: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', expected: '6', isHidden: false },
      { input: '[1]', expected: '1', isHidden: false },
      { input: '[5, 4, -1, 7, 8]', expected: '23', isHidden: true },
      { input: '[-1, -2, -3]', expected: '-1', isHidden: true },
    ],
    examples: [
      { input: '[-2, 1, -3, 4, -1, 2, 1, -5, 4]', output: '6', explanation: '[4, -1, 2, 1] has the largest sum = 6.' },
    ],
    constraints: '1 <= len(nums) <= 10^5',
    xpReward: 175,
    coinReward: 50,
  },
  {
    title: 'Coin Change Problem',
    description: 'Given a JSON array of coin denominations on line 1 and an integer amount on line 2, compute the fewest number of coins needed to make up that amount. If that amount of money cannot be made up by any combination of the coins, print `-1`.',
    language: 'python',
    topic: 'Data Structures & Algorithms',
    learningStage: 8,
    stageName: 'Data Structures & Algorithms',
    order: 32,
    difficulty: 'hard',
    category: 'dynamic-programming',
    testCases: [
      { input: '[1, 2, 5]\n11', expected: '3', isHidden: false },
      { input: '[2]\n3', expected: '-1', isHidden: false },
      { input: '[1]\n0', expected: '0', isHidden: true },
      { input: '[1, 3, 4, 5]\n7', expected: '2', isHidden: true },
    ],
    examples: [
      { input: '[1, 2, 5]\n11', output: '3', explanation: '11 = 5 + 5 + 1 (3 coins).' },
    ],
    constraints: '1 <= coins.length <= 12, 0 <= amount <= 10^4',
    xpReward: 200,
    coinReward: 60,
  },
];
